"use client";

import React, { useState } from "react";
import {
  Sparkles,
  Layers,
  Scale,
  Award,
  BookOpen,
  ChevronRight,
  ChevronDown,
  RotateCcw,
  Search,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Flame,
  Radio,
  Eye,
  Compass,
  Activity,
  Maximize2,
  Grid,
  Shield,
  Zap,
  ArrowRight,
  TrendingUp,
  Droplets,
  Wind,
  Gauge,
  Thermometer,
  Boxes,
  Split,
  TestTube,
  Beaker,
  ZapOff,
  RefreshCw,
  Atom,
  Binary,
  Microscope,
  Pipette,
  FlaskConical,
  CircleDot,
  Dna,
  Magnet,
  Palette,
  Layers3,
  Shapes,
} from "lucide-react";

// ============================================================================
// 1. DATA: 10 NEST MISCONCEPTIONS & TRAPS
// ============================================================================
interface Misconception {
  id: string;
  trap: string;
  reality: string;
  tip: string;
}

const alcTraps: Misconception[] = [
  { id: "t1", trap: "Anisole (Ph-O-CH₃) cleaved with HI produces Chlorobenzene (Ph-Cl) and Methanol.", reality: "Cleavage produces Phenol (Ph-OH) and Methyl Iodide (CH₃I) because the Ph-O bond has partial double-bond character.", tip: "Ph-O bond resists cleavage; I⁻ attacks methyl carbon." },
  { id: "t2", trap: "Reaction of t-butyl bromide with sodium methoxide yields t-butyl methyl ether.", reality: "The 3° halide undergoes E2 elimination with strong base, yielding 2-methylpropene (isobutene).", tip: "To make t-butyl ether, use t-butoxide + methyl bromide." },
  { id: "t3", trap: "In the Lucas test, primary alcohols produce immediate turbidity.", reality: "3° alcohols produce immediate turbidity; 1° alcohols show no turbidity at room temp (need heat).", tip: "Lucas reagent = Conc. HCl + Anhyd. ZnCl₂." },
  { id: "t4", trap: "Phenol is less acidic than ethanol because of its aromatic ring.", reality: "Phenol (pK_a ≈ 10) is 10⁶× MORE ACIDIC than Ethanol (pK_a ≈ 16) due to phenoxide resonance stabilization.", tip: "Phenoxide negative charge delocalizes into aromatic π-system." },
  { id: "t5", trap: "Reimer-Tiemann reaction of phenol utilizes a carbocation intermediate.", reality: "Reimer-Tiemann operates via the neutral, 6-electron electrophile Dichlorocarbene (:CCl₂).", tip: "Generated by α-elimination of HCl from CHCl₃ by base." },
  { id: "t6", trap: "Methanol poisoning is treated by administering sodium bicarbonate.", reality: "Methanol poisoning is treated by administering Intravenous Ethanol (competes for alcohol dehydrogenase).", tip: "Ethanol inhibits formaldehyde/formic acid production." },
  { id: "t7", trap: "Bromination of phenol with bromine water yields 4-bromophenol as the major product.", reality: "Bromine water (Br₂/H₂O) causes polybromination yielding a white ppt of 2,4,6-tribromophenol.", tip: "Monobromination requires non-polar solvents like CS₂ at 273 K." },
  { id: "t8", trap: "The Victor Meyer test for a tertiary alcohol produces a deep blue color.", reality: "1° alcohol = Blood-Red; 2° alcohol = Blue; 3° alcohol = COLORLESS (no α-H).", tip: "Mnemonic: R-B-C (Red, Blue, Colorless)." },
  { id: "t9", trap: "Dehydration of ethanol at 413 K yields ethene.", reality: "Dehydration at 413 K (140°C) yields Diethyl Ether (S_N2). Dehydration at 443 K (170°C) yields Ethene.", tip: "Temperature determines ether vs alkene pathway." },
  { id: "t10", trap: "PCC oxidizes primary alcohols completely to carboxylic acids.", reality: "PCC (Pyridinium Chlorochromate) selectively oxidizes 1° alcohols to ALDEHYDES, stopping at the aldehyde stage.", tip: "Acidified KMnO₄ oxidizes 1° alcohols to carboxylic acids." },
];

// ============================================================================
// 2. DATA: MASTER GLOSSARY (47 DEFINITIONS)
// ============================================================================
interface GlossaryTerm {
  term: string;
  definition: string;
  category: "Alcohols & Hydration" | "Phenols & Acidity" | "Ethers & Mechanisms" | "Reagents & Industrial";
}

const masterGlossary: GlossaryTerm[] = [
  { term: "Absolute Alcohol", definition: "99.5–100% pure ethanol free of water.", category: "Reagents & Industrial" },
  { term: "Acid Growth Hypothesis", definition: "Model proposing auxin activates H⁺-ATPase pumps to acidify cell walls, activating expansins.", category: "Reagents & Industrial" },
  { term: "Acrosin", definition: "A serine protease in the sperm acrosome that digests a path through the Zona Pellucida.", category: "Reagents & Industrial" },
  { term: "Aleurone Layer", definition: "Protein-rich layer of cereal endosperm synthesizing hydrolytic enzymes during germination.", category: "Reagents & Industrial" },
  { term: "Ambident Nucleophile", definition: "A nucleophile possessing two distinct donor atoms capable of attacking an electrophile (e.g., CN⁻, NO₂⁻).", category: "Ethers & Mechanisms" },
  { term: "Anisole", definition: "Methoxybenzene (C₆H₅OCH₃), an aryl ether undergoing o,p-directed electrophilic substitutions.", category: "Ethers & Mechanisms" },
  { term: "Baeyer’s Reagent", definition: "Cold, dilute 1% alkaline KMnO₄ solution used to test for unsaturation by forming cis-1,2-diols.", category: "Reagents & Industrial" },
  { term: "Bento's Rule", definition: "Bent's rule stating more electronegative atoms prefer orbitals with lower s-character.", category: "Reagents & Industrial" },
  { term: "Bitypic / Bivalency", definition: "Werner's concept of primary (ionizable) and secondary (coordination) valencies.", category: "Reagents & Industrial" },
  { term: "Carbocation", definition: "A planar, sp²-hybridized, 6-valence-electron reactive intermediate bearing a positive charge on carbon.", category: "Alcohols & Hydration" },
  { term: "Castle's Intrinsic Factor", definition: "Glycoprotein secreted by gastric parietal cells required for Vitamin B₁₂ absorption in the ileum.", category: "Reagents & Industrial" },
  { term: "Catechol", definition: "1,2-Dihydroxybenzene (benzene-1,2-diol).", category: "Phenols & Acidity" },
  { term: "Cresol", definition: "Methylphenol isomers (o-, m-, p-cresol).", category: "Phenols & Acidity" },
  { term: "Cumene", definition: "Isopropylbenzene (C₆H₅CH(CH₃)₂), the primary feedstock for industrial phenol and acetone co-production.", category: "Phenols & Acidity" },
  { term: "Denatured Alcohol", definition: "Commercial ethanol rendered toxic/undrinkable by adding methanol, pyridine, or copper sulfate.", category: "Reagents & Industrial" },
  { term: "Dichlorocarbene (:CCl₂)", definition: "A neutral 6-electron electrophile generated during the Reimer-Tiemann reaction.", category: "Phenols & Acidity" },
  { term: "Diastereomers", definition: "Non-mirror image stereoisomers possessing different physical and chemical properties.", category: "Alcohols & Hydration" },
  { term: "Dihybrid Cross", definition: "Genetic cross evaluating inheritance of two independent gene pairs (9:3:3:1).", category: "Reagents & Industrial" },
  { term: "Dow Process", definition: "Industrial synthesis of phenol by heating chlorobenzene with molten NaOH at 623 K and 300 atm.", category: "Phenols & Acidity" },
  { term: "Elution", definition: "Process of extracting adsorbed DNA/solute from a gel matrix.", category: "Reagents & Industrial" },
  { term: "Esterification", definition: "Acid-catalyzed condensation reaction between an alcohol/phenol and a carboxylic acid forming an ester.", category: "Alcohols & Hydration" },
  { term: "Fajans’ Rules", definition: "Rules predicting covalent character in ionic bonds based on polarization.", category: "Reagents & Industrial" },
  { term: "Formal Charge", definition: "The formal electronic charge assigned to an atom in a Lewis structure.", category: "Reagents & Industrial" },
  { term: "Glycerol", definition: "Propane-1,2,3-triol, a trihydric viscous alcohol.", category: "Alcohols & Hydration" },
  { term: "Glycol", definition: "Vicinal 1,2-diol (e.g., Ethylene glycol).", category: "Alcohols & Hydration" },
  { term: "Hydroboration-Oxidation", definition: "Two-step alkene hydration yielding overall Anti-Markovnikov syn-addition of water.", category: "Alcohols & Hydration" },
  { term: "Incomplete Dominance", definition: "Inheritance pattern where heterozygous phenotype is an intermediate blend of parental traits.", category: "Reagents & Industrial" },
  { term: "Inversion Temperature", definition: "Temperature below which gas expansion causes cooling (Joule-Thomson effect).", category: "Reagents & Industrial" },
  { term: "Kolbe’s Reaction", definition: "Electrophilic carboxylation of sodium phenoxide with CO₂ under pressure yielding Salicylic acid.", category: "Phenols & Acidity" },
  { term: "Lucas Reagent", definition: "A solution of concentrated HCl and anhydrous ZnCl₂ used to differentiate 1°, 2°, 3° alcohols.", category: "Alcohols & Hydration" },
  { term: "Metamerism", definition: "Isomerism in ethers arising from different alkyl chain distribution on either side of the functional ether oxygen (-O-).", category: "Ethers & Mechanisms" },
  { term: "Methanol", definition: "Methyl alcohol (CH₃OH), highly toxic wood spirit metabolized to formaldehyde in the liver.", category: "Reagents & Industrial" },
  { term: "Nitrenes", definition: "Neutral 6-electron reactive nitrogen intermediates (R-N:).", category: "Reagents & Industrial" },
  { term: "Oxymercuration-Demercuration", definition: "Two-step alkene hydration yielding Markovnikov addition of water without carbocation rearrangement.", category: "Alcohols & Hydration" },
  { term: "Pellicle", definition: "Flexible proteinaceous layer underlying the cell membrane in Euglenoids.", category: "Reagents & Industrial" },
  { term: "Phenoxide Ion", definition: "The resonance-stabilized anion (C₆H₅O⁻) formed by deprotonation of phenol.", category: "Phenols & Acidity" },
  { term: "Picric Acid", definition: "2,4,6-Trinitrophenol, a highly acidic strong organic acid (pK_a = 0.38).", category: "Phenols & Acidity" },
  { term: "Protoplast", definition: "A plant, fungal, or bacterial cell whose cell wall has been completely removed by enzymatic digestion.", category: "Reagents & Industrial" },
  { term: "Pyridinium Chlorochromate (PCC)", definition: "A mild reagent that selectively oxidizes 1° alcohols to aldehydes without further oxidation to acids.", category: "Alcohols & Hydration" },
  { term: "Rectified Spirit", definition: "95.6% ethanol and 4.4% water minimum-boiling azeotropic mixture.", category: "Reagents & Industrial" },
  { term: "Reimer-Tiemann Reaction", definition: "Synthesis of salicylaldehyde by reacting phenol with chloroform and base via dichlorocarbene.", category: "Phenols & Acidity" },
  { term: "Resorcinol", definition: "1,3-Dihydroxybenzene.", category: "Phenols & Acidity" },
  { term: "Salicylaldehyde", definition: "2-Hydroxybenzaldehyde, synthesized via the Reimer-Tiemann reaction.", category: "Phenols & Acidity" },
  { term: "Salicylic Acid", definition: "2-Hydroxybenzoic acid, synthesized via Kolbe's reaction; precursor for Aspirin.", category: "Phenols & Acidity" },
  { term: "Suberin", definition: "Hydrophobic fatty polymer deposited in Casparian strips and cork.", category: "Reagents & Industrial" },
  { term: "Victor Meyer Test", definition: "A colorimetric test distinguishing 1° (Red), 2° (Blue), and 3° (Colorless) alcohols.", category: "Alcohols & Hydration" },
  { term: "Williamson Ether Synthesis", definition: "S_N2 reaction of 1° alkyl halides with sodium alkoxides yielding symmetrical or unsymmetrical ethers.", category: "Ethers & Mechanisms" },
];

// ============================================================================
// 3. DATA: ALL 20 NEST ASSESSMENT QUESTIONS
// ============================================================================
interface MCQOption {
  key: string;
  text: string;
}

interface MCQ {
  id: number;
  part: "A" | "B";
  question: string;
  options: MCQOption[];
  correctKeys: string[];
  type: "single" | "multi";
  explanation: string;
}

const mcqData: MCQ[] = [
  {
    id: 1,
    part: "A",
    question: "An unknown monohydric alcohol X (C₅H₁₂O) is subjected to the Victor Meyer test, producing an intense Blood-Red solution. When alcohol X is passed over hot metallic copper at 573 K, it yields an aldehyde Y. Oxidation of X with PCC produces Y, which upon treatment with dilute NaOH undergoes an Aldol condensation. What is the structural formula and IUPAC name of alcohol X?",
    options: [
      { key: "A", text: "2-Methylbutan-2-ol" },
      { key: "B", text: "3-Methylbutan-1-ol" },
      { key: "C", text: "2,2-Dimethylpropan-1-ol (Neopentyl alcohol)" },
      { key: "D", text: "Pentan-2-ol" },
    ],
    correctKeys: ["B"],
    type: "single",
    explanation: "1. Victor Meyer Blood-Red color confirms a Primary (1°) alcohol. 2. Hot Cu at 573 K converts 1° alcohol to aldehyde Y. 3. Aldehyde Y undergoes Aldol condensation ⟹ must possess α-hydrogens. 4. Neopentyl alcohol gives pivalaldehyde (0 α-H, no Aldol). 3-Methylbutan-1-ol gives 3-methylbutanal (2 α-H, undergoes Aldol).",
  },
  {
    id: 2,
    part: "A",
    question: "During the industrial production of Phenol via the Cumene Hydroperoxide process, Benzene is reacted with Propene in the presence of H₃PO₄ catalyst at 523 K to yield Cumene. Cumene is oxidized with air to Cumene Hydroperoxide, which is cleaved with dilute H₂SO₄. What is the valuable organic co-product formed alongside Phenol in this industrial synthesis?",
    options: [
      { key: "A", text: "Acetaldehyde" },
      { key: "B", text: "Acetone (Propanone)" },
      { key: "C", text: "Benzaldehyde" },
      { key: "D", text: "Ethanol" },
    ],
    correctKeys: ["B"],
    type: "single",
    explanation: "Acid cleavage of Cumene Hydroperoxide (C₆H₅-C(CH₃)₂-O-O-H) quantitatively yields Phenol (C₆H₅OH) and Acetone (CH₃COCH₃).",
  },
  {
    id: 3,
    part: "A",
    question: "Arrange the following phenolic compounds in order of INCREASING Acidic Strength (lowest pK_a / highest acidity): 1: Phenol, 2: p-Nitrophenol, 3: p-Cresol (4-Methylphenol), 4: 2,4,6-Trinitrophenol (Picric Acid)",
    options: [
      { key: "A", text: "3 < 1 < 2 < 4" },
      { key: "B", text: "4 < 2 < 1 < 3" },
      { key: "C", text: "1 < 3 < 2 < 4" },
      { key: "D", text: "3 < 2 < 1 < 4" },
    ],
    correctKeys: ["A"],
    type: "single",
    explanation: "EDG (-CH₃) in p-cresol decreases acidity (3). EWG (-NO₂) in p-nitrophenol increases acidity (2). 3 nitro groups in Picric Acid (4) give extreme acidity (pK_a = 0.38). Order: 3 < 1 < 2 < 4.",
  },
  {
    id: 4,
    part: "A",
    question: "What is the active electrophilic species generated during the Reimer-Tiemann reaction of Phenol with Chloroform (CHCl₃) and aqueous NaOH to synthesize Salicylaldehyde?",
    options: [
      { key: "A", text: "Trichloromethyl carbocation (CCl₃⁺)" },
      { key: "B", text: "Dichlorocarbene (:CCl₂)" },
      { key: "C", text: "Formyl cation (CHO⁺)" },
      { key: "D", text: "Chloronium ion (Cl⁺)" },
    ],
    correctKeys: ["B"],
    type: "single",
    explanation: "Base abstracts proton from CHCl₃ to form :CCl₃⁻, which undergoes α-elimination of Cl⁻ to yield the neutral, 6-electron reactive intermediate Dichlorocarbene (:CCl₂).",
  },
  {
    id: 5,
    part: "A",
    question: "A student attempts to prepare tert-Butyl Ethyl Ether by reacting 2-bromo-2-methylpropane (3° alkyl halide) with Sodium Ethoxide (NaOCH₂CH₃) in ethanol. What major organic product is actually recovered from this reaction mixture?",
    options: [
      { key: "A", text: "tert-Butyl Ethyl Ether via S_N2" },
      { key: "B", text: "2-Methylpropene (Isobutene) via E2 elimination" },
      { key: "C", text: "Diethyl Ether via substitution" },
      { key: "D", text: "2-Methylpropan-2-ol via S_N1" },
    ],
    correctKeys: ["B"],
    type: "single",
    explanation: "Strong base (EtO⁻) with 3° alkyl halide causes E2 elimination to dominate completely over substitution, yielding 2-Methylpropene (Isobutene).",
  },
  {
    id: 6,
    part: "A",
    question: "What organic products are formed when Anisole (Methoxybenzene, Ph-O-CH₃) is cleaved by heating with 1 equivalent of concentrated Hydroiodic Acid (HI)?",
    options: [
      { key: "A", text: "Chlorobenzene + Methanol" },
      { key: "B", text: "Phenol (C₆H₅OH) + Methyl Iodide (CH₃I)" },
      { key: "C", text: "Iodobenzene (C₆H₅I) + Methanol (CH₃OH)" },
      { key: "D", text: "Benzene + Formaldehyde" },
    ],
    correctKeys: ["B"],
    type: "single",
    explanation: "The C_aryl-O bond has partial double-bond character and cannot be cleaved. Iodide attacks methyl carbon via S_N2, yielding Phenol and Methyl Iodide.",
  },
  {
    id: 7,
    part: "A",
    question: "An unknown alcohol A (C₄H₁₀O) gives an immediate turbidity when shaken with Lucas Reagent (Conc. HCl + Anhydrous ZnCl₂) at room temperature. What is the structural formula and IUPAC name of alcohol A?",
    options: [
      { key: "A", text: "Butan-1-ol" },
      { key: "B", text: "Butan-2-ol" },
      { key: "C", text: "2-Methylpropan-2-ol (tert-Butyl alcohol)" },
      { key: "D", text: "2-Methylpropan-1-ol" },
    ],
    correctKeys: ["C"],
    type: "single",
    explanation: "Immediate turbidity in Lucas test at room temperature is diagnostic of a 3° alcohol. 2-Methylpropan-2-ol is the only 3° isomer of C₄H₁₀O.",
  },
  {
    id: 8,
    part: "A",
    question: "When Phenol is treated with Bromine Water (Br₂ / H₂O) at room temperature, a dense precipitate P is formed immediately. What is the chemical identity and color of precipitate P?",
    options: [
      { key: "A", text: "4-Bromophenol; Pale yellow" },
      { key: "B", text: "2,4,6-Tribromophenol; White precipitate" },
      { key: "C", text: "2-Bromophenol; Brown liquid" },
      { key: "D", text: "Bromobenzene; Colorless liquid" },
    ],
    correctKeys: ["B"],
    type: "single",
    explanation: "Water polarizes phenol into phenoxide, activating all o,p positions and yielding 2,4,6-Tribromophenol as a White Precipitate (↓).",
  },
  {
    id: 9,
    part: "A",
    question: "What organic compound is produced when Salicylic Acid is heated with Acetic Anhydride in the presence of a few drops of concentrated H₂SO₄?",
    options: [
      { key: "A", text: "Salicylaldehyde" },
      { key: "B", text: "Aspirin (Acetylsalicylic Acid)" },
      { key: "C", text: "Methyl Salicylate (Oil of Wintergreen)" },
      { key: "D", text: "Phenyl Salicylate (Salol)" },
    ],
    correctKeys: ["B"],
    type: "single",
    explanation: "Acetylation of the phenolic -OH group of Salicylic Acid with Acetic Anhydride produces Acetylsalicylic Acid (Aspirin).",
  },
  {
    id: 10,
    part: "A",
    question: "What is the major product obtained when 2.0 moles of Ethanol are heated with concentrated H₂SO₄ at 413 K (140°C) versus 443 K (170°C)?",
    options: [
      { key: "A", text: "At 413 K: Diethyl Ether; At 443 K: Ethene" },
      { key: "B", text: "At 413 K: Ethene; At 443 K: Diethyl Ether" },
      { key: "C", text: "At both temperatures: Ethyl hydrogen sulfate" },
      { key: "D", text: "At 413 K: Ethane; At 443 K: Acetaldehyde" },
    ],
    correctKeys: ["A"],
    type: "single",
    explanation: "At 413 K (140°C): S_N2 condensation yields Diethyl Ether. At 443 K (170°C): E1 elimination yields Ethene.",
  },
  {
    id: 11,
    part: "B",
    question: "Which of the following experimental tests can be used to explicitly distinguish a Primary (1°) Alcohol from a Tertiary (3°) Alcohol? (Select all that apply)",
    options: [
      { key: "A", text: "Lucas Test (Conc. HCl + Anhyd. ZnCl₂)" },
      { key: "B", text: "Victor Meyer Test (R-B-C test)" },
      { key: "C", text: "Dehydrogenation over hot copper at 573 K" },
      { key: "D", text: "Neutral FeCl₃ Test" },
    ],
    correctKeys: ["A", "B", "C"],
    type: "multi",
    explanation: "• A, B, C distinguish alcohol classes. • D (neutral FeCl₃) tests specifically for Phenols.",
  },
  {
    id: 12,
    part: "B",
    question: "Select the valid statements regarding the acidity of Phenol relative to Ethanol: (Select all that apply)",
    options: [
      { key: "A", text: "Phenol (pK_a ≈ 9.98) is much more acidic than Ethanol (pK_a ≈ 16.0)." },
      { key: "B", text: "Deprotonation of phenol yields the Phenoxide ion, which is resonance-stabilized by delocalizing negative charge into the aromatic ring." },
      { key: "C", text: "Deprotonation of ethanol yields the Ethoxide ion, where negative charge is localized on oxygen and destabilized by the +I effect of the ethyl group." },
      { key: "D", text: "Phenol reacts with aqueous NaHCO₃ solution to liberate CO₂ gas." },
    ],
    correctKeys: ["A", "B", "C"],
    type: "multi",
    explanation: "• A, B, C are correct. • D is false: Phenol (pK_a ≈ 10) is weaker than carbonic acid (pK_a ≈ 6.35) and cannot liberate CO₂ from NaHCO₃.",
  },
  {
    id: 13,
    part: "B",
    question: "Which of the following reactions represent valid synthetic preparations of PHENOL? (Select all that apply)",
    options: [
      { key: "A", text: "Hydrolysis of Chlorobenzene with NaOH at 623 K and 300 atm pressure (Dow Process)." },
      { key: "B", text: "Air oxidation of Cumene to Cumene Hydroperoxide followed by cleavage with dilute H₂SO₄." },
      { key: "C", text: "Hydrolysis of Benzenediazonium chloride by warming with water." },
      { key: "D", text: "Hydrolysis of Ethyl Acetate with dilute HCl." },
    ],
    correctKeys: ["A", "B", "C"],
    type: "multi",
    explanation: "• A, B, C are valid phenol syntheses. • D yields ethanol and acetic acid.",
  },
  {
    id: 14,
    part: "B",
    question: "Select the correct options regarding the Reimer-Tiemann and Kolbe's reactions of Phenol: (Select all that apply)",
    options: [
      { key: "A", text: "Reimer-Tiemann reaction uses CHCl₃ + NaOH to convert phenol into Salicylaldehyde." },
      { key: "B", text: "The active electrophile in the Reimer-Tiemann reaction is Dichlorocarbene (:CCl₂)." },
      { key: "C", text: "Kolbe's reaction uses CO₂ + NaOH under pressure to convert phenol into Salicylic Acid." },
      { key: "D", text: "Both reactions proceed via an S_N2 nucleophilic substitution mechanism on an sp³ carbon." },
    ],
    correctKeys: ["A", "B", "C"],
    type: "multi",
    explanation: "• A, B, C are accurate. • D is false: Both reactions are Electrophilic Aromatic Substitutions (S_EAr) on the ring.",
  },
  {
    id: 15,
    part: "B",
    question: "Which of the following unsymmetrical ethers, when cleaved by 1 equivalent of concentrated HI, yield tert-Butyl Iodide ((CH₃)₃C-I) via an S_N1 mechanism? (Select all that apply)",
    options: [
      { key: "A", text: "tert-Butyl Methyl Ether ((CH₃)₃C-O-CH₃)" },
      { key: "B", text: "tert-Butyl Ethyl Ether ((CH₃)₃C-O-CH₂CH₃)" },
      { key: "C", text: "Anisole (C₆H₅-O-CH₃)" },
      { key: "D", text: "Diethyl Ether (CH₃CH₂-O-CH₂CH₃)" },
    ],
    correctKeys: ["A", "B"],
    type: "multi",
    explanation: "• A and B contain 3° t-butyl groups forming 3° carbocations that combine with I⁻. • C gives phenol + CH₃I. • D gives ethyl iodide + ethanol.",
  },
  {
    id: 16,
    part: "B",
    question: "Select the correct options regarding the Williamson Ether Synthesis: (Select all that apply)",
    options: [
      { key: "A", text: "It involves an S_N2 attack of an alkoxide ion (R'O⁻) on an alkyl halide (R-X)." },
      { key: "B", text: "High yields of mixed ethers are obtained when the alkyl halide is primary (1°) or methyl." },
      { key: "C", text: "Using a tertiary (3°) alkyl halide results predominantly in E2 elimination to yield an alkene." },
      { key: "D", text: "Phenols can be converted to aryl ethers by reacting sodium phenoxide with alkyl halides." },
    ],
    correctKeys: ["A", "B", "C", "D"],
    type: "multi",
    explanation: "All four options correctly characterize Williamson ether synthesis parameters and constraints.",
  },
  {
    id: 17,
    part: "B",
    question: "Which of the following statements regarding Methanol and Ethanol toxicology/properties are TRUE? (Select all that apply)",
    options: [
      { key: "A", text: "Methanol is metabolized in the liver by alcohol dehydrogenase to Formaldehyde and Formic acid, causing optic nerve damage and blindness." },
      { key: "B", text: "Ethanol poisoning is treated by intravenous administration of methanol." },
      { key: "C", text: "Denatured alcohol is ethanol mixed with toxic methanol, pyridine, and copper sulfate to prevent human consumption." },
      { key: "D", text: "Methanol is also known as 'Wood Spirit'." },
    ],
    correctKeys: ["A", "C", "D"],
    type: "multi",
    explanation: "• A, C, D are true. • B is false: Methanol poisoning is treated with ethanol.",
  },
  {
    id: 18,
    part: "B",
    question: "Which of the following reagents selectively oxidize a primary alcohol (R-CH₂OH) to an Aldehyde (R-CHO) without further oxidation to a carboxylic acid? (Select all that apply)",
    options: [
      { key: "A", text: "Pyridinium Chlorochromate (PCC) in CH₂Cl₂" },
      { key: "B", text: "Pyridinium Dichromate (PDC) in CH₂Cl₂" },
      { key: "C", text: "Copper catalyst at 573 K (Cu / 300°C)" },
      { key: "D", text: "Acidified Potassium Permanganate (KMnO₄ / H⁺)" },
    ],
    correctKeys: ["A", "B", "C"],
    type: "multi",
    explanation: "• PCC, PDC, and hot Cu stop oxidation cleanly at the Aldehyde stage. • KMnO₄/H⁺ oxidizes directly to Carboxylic Acid.",
  },
  {
    id: 19,
    part: "B",
    question: "Select the valid statements regarding the physical properties of Alcohols and Phenols: (Select all that apply)",
    options: [
      { key: "A", text: "Alcohols have higher boiling points than isomeric ethers due to intermolecular hydrogen bonding." },
      { key: "B", text: "Among isomeric alcohols, 1° alcohols have higher boiling points than 3° alcohols due to larger surface area." },
      { key: "C", text: "o-Nitrophenol is steam-volatile because it forms Intramolecular Hydrogen Bonds." },
      { key: "D", text: "p-Nitrophenol has a lower boiling point than o-nitrophenol." },
    ],
    correctKeys: ["A", "B", "C"],
    type: "multi",
    explanation: "• A, B, C are correct. • D is false: p-Nitrophenol forms intermolecular H-bonds, giving it a higher boiling point.",
  },
  {
    id: 20,
    part: "B",
    question: "Which of the following reactions of Phenol result in the formation of a NEW CARBON-CARBON BOND on the aromatic ring? (Select all that apply)",
    options: [
      { key: "A", text: "Kolbe’s Reaction (formation of Salicylic acid)" },
      { key: "B", text: "Reimer-Tiemann Reaction (formation of Salicylaldehyde)" },
      { key: "C", text: "Friedel-Crafts Alkylation with CH₃Cl / AlCl₃" },
      { key: "D", text: "Reaction with neutral FeCl₃ solution" },
    ],
    correctKeys: ["A", "B", "C"],
    type: "multi",
    explanation: "• Kolbe (C-COOH), Reimer-Tiemann (C-CHO), and Friedel-Crafts (C-CH₃) form ring C-C bonds. • Neutral FeCl₃ forms an Fe-O coordinate bond.",
  },
];

// ============================================================================
// MAIN COMPONENT
// ============================================================================
type Tab = "classification-hydration" | "diagnostic-tests" | "oxidation-dehydration" | "methanol-ethanol" | "phenol-acidity" | "phenol-reactions" | "ethers-cleavage-calculator" | "traps" | "glossary" | "selftest";

export const AlcoholsPhenolsEthersDiagram: React.FC = () => {
  const [activeTab, setActiveTab] = useState<Tab>("classification-hydration");
  const [activeTrapId, setActiveTrapId] = useState<string | null>(null);

  // Interactive Ether Cleavage Simulator State
  const [selectedEther, setSelectedEther] = useState<string>("anisole");
  const etherSamples: Record<string, { name: string; structure: string; mechanism: "S_N1" | "S_N2" | "Aromatic S_N2"; products: string; explanation: string }> = {
    anisole: {
      name: "Anisole (Methoxybenzene)",
      structure: "C₆H₅-O-CH₃",
      mechanism: "Aromatic S_N2",
      products: "Phenol (C₆H₅OH) + Methyl Iodide (CH₃I)",
      explanation: "The C_aryl-O bond possesses partial double-bond character due to resonance (+M). It CANNOT be cleaved by I⁻. Iodide attacks the less hindered methyl carbon via S_N2, yielding Phenol and CH₃I.",
    },
    tbutyl_methyl: {
      name: "tert-Butyl Methyl Ether",
      structure: "(CH₃)₃C-O-CH₃",
      mechanism: "S_N1",
      products: "tert-Butyl Iodide ((CH₃)₃C-I) + Methanol (CH₃OH)",
      explanation: "Protonation yields oxonium ion. Because a 3° alkyl group is present, it cleaves via S_N1 forming a stable 3° carbocation ((CH₃)₃C⁺), which reacts with I⁻ to give t-butyl iodide.",
    },
    diethyl: {
      name: "Diethyl Ether",
      structure: "CH₃CH₂-O-CH₂CH₃",
      mechanism: "S_N2",
      products: "Ethyl Iodide (CH₃CH₂I) + Ethanol (CH₃CH₂OH)",
      explanation: "Symmetrical primary ether. Protonated ether is attacked by I⁻ via a standard S_N2 mechanism on the 1° carbon.",
    },
    ethyl_methyl: {
      name: "Ethyl Methyl Ether",
      structure: "CH₃-O-CH₂CH₃",
      mechanism: "S_N2",
      products: "Methyl Iodide (CH₃I) + Ethanol (CH₃CH₂OH)",
      explanation: "Unsymmetrical 1°/1° ether. Iodide attacks the smaller, LESS sterically hindered methyl group via S_N2, releasing ethanol.",
    },
  };

  // Glossary filter state
  const [glossarySearch, setGlossarySearch] = useState("");
  const [glossaryCategory, setGlossaryCategory] = useState<string>("All");

  // Self-test state
  const [currentQ, setCurrentQ] = useState(0);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, string[]>>({});
  const [submitted, setSubmitted] = useState<Record<number, boolean>>({});
  const [score, setScore] = useState<number | null>(null);
  const [testPartFilter, setTestPartFilter] = useState<"ALL" | "A" | "B">("ALL");

  const currentMCQ = mcqData[currentQ];

  const filteredGlossary = masterGlossary.filter((item) => {
    const matchesSearch = item.term.toLowerCase().includes(glossarySearch.toLowerCase()) || item.definition.toLowerCase().includes(glossarySearch.toLowerCase());
    const matchesCategory = glossaryCategory === "All" || item.category === glossaryCategory;
    return matchesSearch && matchesCategory;
  });

  function toggleAnswer(qIndex: number, key: string, type: "single" | "multi") {
    if (submitted[qIndex]) return;
    setSelectedAnswers((prev) => {
      const current = prev[qIndex] || [];
      if (type === "single") return { ...prev, [qIndex]: [key] };
      if (current.includes(key)) return { ...prev, [qIndex]: current.filter((k) => k !== key) };
      return { ...prev, [qIndex]: [...current, key] };
    });
  }

  function submitAnswer(qIndex: number) {
    setSubmitted((prev) => ({ ...prev, [qIndex]: true }));
  }

  function computeScore() {
    let correct = 0;
    mcqData.forEach((q, i) => {
      const sel = selectedAnswers[i] || [];
      if (sel.length === q.correctKeys.length && q.correctKeys.every((k) => sel.includes(k))) correct++;
    });
    setScore(correct);
  }

  function resetSelfTest() {
    setSelectedAnswers({});
    setSubmitted({});
    setScore(null);
    setCurrentQ(0);
  }

  const tabs: { id: Tab; label: string; icon: React.ReactNode }[] = [
    { id: "classification-hydration", label: "Classes & Hydration", icon: <Atom className="w-3.5 h-3.5 shrink-0" /> },
    { id: "diagnostic-tests", label: "Diagnostic Tests", icon: <Pipette className="w-3.5 h-3.5 shrink-0" /> },
    { id: "oxidation-dehydration", label: "Oxidation & E1 Dehydration", icon: <Flame className="w-3.5 h-3.5 shrink-0" /> },
    { id: "methanol-ethanol", label: "Industrial & Toxicology", icon: <Shield className="w-3.5 h-3.5 shrink-0" /> },
    { id: "phenol-acidity", label: "Phenol Acidity", icon: <Scale className="w-3.5 h-3.5 shrink-0" /> },
    { id: "phenol-reactions", label: "Phenol Reactions", icon: <Split className="w-3.5 h-3.5 shrink-0" /> },
    { id: "ethers-cleavage-calculator", label: "Ethers & HI Cleavage", icon: <FlaskConical className="w-3.5 h-3.5 shrink-0" /> },
    { id: "traps", label: "10 NEST Traps", icon: <AlertTriangle className="w-3.5 h-3.5 shrink-0" /> },
    { id: "glossary", label: "Master Glossary", icon: <BookOpen className="w-3.5 h-3.5 shrink-0" /> },
    { id: "selftest", label: "NEST 20-Q Test", icon: <Award className="w-3.5 h-3.5 shrink-0" /> },
  ];

  return (
    <div className="my-4 sm:my-8 rounded-2xl sm:rounded-3xl bg-gradient-to-b from-white via-slate-50 to-emerald-50/20 border border-slate-200/90 p-2.5 sm:p-7 shadow-xs space-y-4 sm:space-y-6 select-none w-full">

      {/* HEADER */}
      <div className="flex flex-col items-center text-center space-y-2.5 max-w-2xl mx-auto w-full">
        <span className="px-3 py-0.5 rounded-full text-[10px] font-black uppercase tracking-wider bg-emerald-100 text-emerald-900 border border-emerald-200 shadow-2xs flex items-center gap-1.5">
          <Sparkles className="w-3 h-3 text-emerald-600" />
          CHEMISTRY INTERACTIVE MODULE — ALCOHOLS, PHENOLS &amp; ETHERS (CLASS XII / UNIT XVI)
        </span>
        <div className="p-3 sm:p-5 rounded-xl sm:rounded-2xl bg-white border border-slate-200/90 shadow-2xs w-full space-y-1">
          <h3 className="text-base sm:text-2xl font-black text-slate-900 tracking-tight flex items-center justify-center gap-1.5 sm:gap-2">
            <FlaskConical className="w-5 h-5 sm:w-6 sm:h-6 text-emerald-600 shrink-0" />
            ALCOHOLS, PHENOLS &amp; ETHERS: HYDRATION, LUCAS/VICTOR MEYER, CUMENE, KOLBE &amp; HI CLEAVAGE
          </h3>
          <p className="text-[11px] sm:text-sm font-semibold text-slate-600 leading-snug">
            Alcohol Classifications · OMDM vs HBO · Lucas &amp; Victor Meyer Diagnostics · Phenol Acidity &amp; Cumene Process · Williamson Synthesis &amp; HI Cleavage Kinetics
          </p>
        </div>
      </div>

      {/* NAVIGATION TABS */}
      <div className="grid grid-cols-2 sm:flex sm:flex-wrap items-center justify-center gap-1.5 sm:gap-2 p-1 sm:p-1.5 bg-slate-100/90 rounded-xl sm:rounded-2xl border border-slate-200 w-full max-w-5xl mx-auto">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`px-2 py-1.5 sm:px-3 sm:py-2 rounded-lg sm:rounded-xl text-[10px] sm:text-xs font-black transition-all flex items-center justify-center gap-1.5 ${
              activeTab === tab.id
                ? "bg-white text-slate-950 shadow-xs border border-slate-200"
                : "text-slate-600 hover:text-slate-900"
            }`}
          >
            {tab.icon}
            <span>{tab.label}</span>
          </button>
        ))}
      </div>

      {/* TAB 1: CLASSIFICATIONS & HYDRATION */}
      {activeTab === "classification-hydration" && (
        <div className="space-y-4 sm:space-y-5 max-w-4xl mx-auto w-full">
          <div className="p-3.5 sm:p-5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-3">
            <h4 className="text-sm sm:text-base font-black text-slate-900 flex items-center gap-2">
              <Atom className="w-4 h-4 text-emerald-600 shrink-0" />
              Alcohol Classifications, Physical Trends &amp; Alkene Hydration Pathways
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-[10px]">
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 space-y-1.5">
                <span className="font-black text-slate-900 uppercase">Alcohol Classifications &amp; Boiling Points</span>
                <p className="text-slate-800 font-semibold">• <strong>1° Alcohol:</strong> R-CH₂OH; <strong>2°:</strong> R₂CHOH; <strong>3°:</strong> R₃COH; <strong>Polyhydric:</strong> Glycols, Glycerol.</p>
                <p className="text-slate-800 font-semibold">• <strong>Boiling Point Trend:</strong> 1° &gt; 2° &gt; 3° (Branching reduces surface area and van der Waals forces).</p>
                <p className="text-slate-700">Extensive intermolecular H-bonding gives much higher BP than isomeric ethers or alkanes.</p>
              </div>
              <div className="p-3 rounded-xl bg-emerald-50/70 border border-emerald-200 space-y-1.5">
                <span className="font-black text-emerald-950 uppercase">Synthetic Hydration Pathways</span>
                <p className="text-emerald-900 font-semibold">• <strong>Acid-Catalyzed (H⁺/H₂O):</strong> Markovnikov; carbocation; <strong>Prone to rearrangements!</strong></p>
                <p className="text-emerald-900 font-semibold">• <strong>OMDM:</strong> Markovnikov; cyclic mercurinium ion; <strong>NO rearrangements!</strong></p>
                <p className="text-emerald-950 font-bold">• <strong>HBO (BH₃·THF, H₂O₂/OH⁻):</strong> Anti-Markovnikov; <strong>Syn-addition</strong> of H₂O.</p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: DIAGNOSTIC TESTS */}
      {activeTab === "diagnostic-tests" && (
        <div className="space-y-4 sm:space-y-5 max-w-4xl mx-auto w-full">
          <div className="p-3.5 sm:p-5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-3">
            <h4 className="text-sm sm:text-base font-black text-slate-900 flex items-center gap-2">
              <Pipette className="w-4 h-4 text-blue-600 shrink-0" />
              Lucas Test, Victor Meyer (R-B-C) Test, &amp; Hot Copper Catalysis
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 text-[10px]">
              <div className="p-2.5 rounded-xl bg-blue-50/70 border border-blue-200 space-y-1">
                <span className="font-black text-blue-950 block uppercase">1. Lucas Test (HCl + ZnCl₂)</span>
                <p className="text-blue-900 font-semibold">• <strong>3° Alcohol:</strong> Immediate turbidity at room temp.</p>
                <p className="text-blue-900 font-semibold">• <strong>2° Alcohol:</strong> Turbidity in 5–10 minutes.</p>
                <p className="text-blue-900 font-semibold">• <strong>1° Alcohol:</strong> Clear at room temp; turbid on heat.</p>
              </div>
              <div className="p-2.5 rounded-xl bg-purple-50/70 border border-purple-200 space-y-1">
                <span className="font-black text-purple-950 block uppercase">2. Victor Meyer (R-B-C)</span>
                <p className="text-purple-900 font-semibold">• <strong>1° Alcohol:</strong> Blood-Red (Nitrolic acid).</p>
                <p className="text-purple-900 font-semibold">• <strong>2° Alcohol:</strong> Blue (Pseudonitrol).</p>
                <p className="text-purple-900 font-semibold">• <strong>3° Alcohol:</strong> Colorless (No α-H).</p>
              </div>
              <div className="p-2.5 rounded-xl bg-amber-50/70 border border-amber-200 space-y-1">
                <span className="font-black text-amber-950 block uppercase">3. Cu at 573 K (300°C)</span>
                <p className="text-amber-900 font-semibold">• <strong>1° Alcohol:</strong> R-CHO (Aldehyde) + H₂.</p>
                <p className="text-amber-900 font-semibold">• <strong>2° Alcohol:</strong> R₂C=O (Ketone) + H₂.</p>
                <p className="text-amber-950 font-bold">• <strong>3° Alcohol:</strong> Alkene (Isobutene) + H₂O (Dehydration!).</p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 3: OXIDATION & E1 DEHYDRATION */}
      {activeTab === "oxidation-dehydration" && (
        <div className="space-y-4 sm:space-y-5 max-w-4xl mx-auto w-full">
          <div className="p-3.5 sm:p-5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-3">
            <h4 className="text-sm sm:text-base font-black text-slate-900 flex items-center gap-2">
              <Flame className="w-4 h-4 text-rose-600 shrink-0" />
              Selective Oxidation Cascades &amp; Acid-Catalyzed E1 Dehydration
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-[10px]">
              <div className="p-2.5 rounded-xl bg-slate-50 border border-slate-200 space-y-1">
                <span className="font-black text-slate-900 block uppercase">Selective Oxidation Reagents</span>
                <p className="text-slate-800 font-semibold">• <strong>PCC / PDC in CH₂Cl₂:</strong> Selectively oxidizes 1° alcohols to <strong>Aldehydes</strong> (stops over-oxidation).</p>
                <p className="text-slate-800 font-semibold">• <strong>Acidified KMnO₄ / K₂Cr₂O₇:</strong> Converts 1° alcohols to <strong>Carboxylic Acids</strong>.</p>
                <p className="text-slate-800 font-semibold">• <strong>2° Alcohols:</strong> Oxidize to Ketones.</p>
                <p className="text-slate-800 font-semibold">• <strong>3° Alcohols:</strong> Resist mild oxidation; cleave C-C bonds with hot KMnO₄/H⁺.</p>
              </div>
              <div className="p-2.5 rounded-xl bg-rose-50/70 border border-rose-200 space-y-1">
                <span className="font-black text-rose-950 block uppercase">Acid-Catalyzed E1 Dehydration</span>
                <p className="text-rose-900 font-semibold">• Step 1 (Fast): Protonation of -OH to -OH₂⁺ (Oxonium ion).</p>
                <p className="text-rose-900 font-semibold">• Step 2 (RDS): Loss of H₂O to form <strong>Carbocation Intermediate</strong>.</p>
                <p className="text-rose-900 font-semibold">• Step 3 (Fast): Loss of β-H⁺ to form Alkene.</p>
                <p className="text-rose-950 font-bold">• Ease of Dehydration: 3° &gt; 2° &gt; 1° (Carbocation stability).</p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 4: INDUSTRIAL & TOXICOLOGY */}
      {activeTab === "methanol-ethanol" && (
        <div className="space-y-4 sm:space-y-5 max-w-4xl mx-auto w-full">
          <div className="p-3.5 sm:p-5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-3">
            <h4 className="text-sm sm:text-base font-black text-slate-900 flex items-center gap-2">
              <Shield className="w-4 h-4 text-teal-600 shrink-0" />
              Methanol Synthesis, Biochemical Toxicity, &amp; Denatured Ethanol
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-[10px]">
              <div className="p-2.5 rounded-xl bg-teal-50/70 border border-teal-200 space-y-1">
                <span className="font-black text-teal-950 uppercase block">Methanol Synthesis &amp; Toxicity</span>
                <p className="text-teal-900 font-semibold">• Synthesis: CO + 2H₂ ──[ZnO-Cr₂O₃, 200–300 atm, 573–673 K]──► CH₃OH ('Wood Spirit').</p>
                <p className="text-teal-900 font-semibold">• Metabolism: Alcohol dehydrogenase converts CH₃OH ──► HCHO (Formaldehyde) ──► HCOOH (Formic Acid).</p>
                <p className="text-teal-950 font-bold">• Pathology: Retinal protein coagulation ──► Blindness; Acidosis ──► Death.</p>
                <p className="text-teal-900 font-semibold">• Antidote: <strong>Intravenous Ethanol</strong> (competitive inhibitor).</p>
              </div>
              <div className="p-2.5 rounded-xl bg-slate-50 border border-slate-200 space-y-1">
                <span className="font-black text-slate-900 uppercase block">Denatured Alcohol Formulation</span>
                <p className="text-slate-800 font-semibold">• Ethanol made unfit for human consumption by adding:</p>
                <p className="text-slate-800 font-semibold">1. 5% Methanol (toxic wood spirit)</p>
                <p className="text-slate-800 font-semibold">2. Pyridine (imparts foul odor)</p>
                <p className="text-slate-800 font-semibold">3. Copper Sulfate (diagnostic blue color)</p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 5: PHENOL ACIDITY */}
      {activeTab === "phenol-acidity" && (
        <div className="space-y-4 sm:space-y-5 max-w-4xl mx-auto w-full">
          <div className="p-3.5 sm:p-5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-3">
            <h4 className="text-sm sm:text-base font-black text-slate-900 flex items-center gap-2">
              <Scale className="w-4 h-4 text-indigo-600 shrink-0" />
              Phenol Acidity, Phenoxide Resonance &amp; Substituent Effects
            </h4>
            <div className="p-2.5 rounded-xl bg-indigo-50/70 border border-indigo-200 text-[10px] space-y-1">
              <span className="font-black text-indigo-950 block">Acidity Hierarchy: Picric Acid (0.38) &gt; Phenol (9.98) &gt; Water (15.7) &gt; Ethanol (16.0)</span>
              <p className="text-indigo-900 font-semibold">• Phenols are 10⁶× more acidic than alcohols because the Phenoxide Ion (Ph-O⁻) is heavily resonance-stabilized across 4 canonical structures.</p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 text-[10px]">
              <div className="p-2.5 rounded-xl bg-slate-50 border border-slate-200 space-y-1 font-mono font-bold text-slate-900">
                <span className="text-[9px] uppercase text-slate-600 block">Nitrophenol Acidity Spectrum (pK_a)</span>
                <p>• Picric Acid (2,4,6-trinitro): 0.38</p>
                <p>• 2,4-Dinitrophenol: 4.0</p>
                <p>• p-Nitrophenol: 7.15</p>
                <p>• o-Nitrophenol: 7.23</p>
                <p>• m-Nitrophenol: 8.35</p>
                <p>• Unsubstituted Phenol: 9.98</p>
              </div>
              <div className="p-2.5 rounded-xl bg-amber-50/70 border border-amber-200 space-y-1">
                <span className="font-black text-amber-950 uppercase block">o- vs p-Nitrophenol Paradox</span>
                <p className="text-amber-900 font-semibold">• <strong>p-Nitrophenol:</strong> Slightly more acidic; intermolecular H-bonds (higher BP).</p>
                <p className="text-amber-950 font-bold">• <strong>o-Nitrophenol:</strong> Intramolecular H-bonds hinder deprotonation &amp; confer <strong>Steam Volatility</strong>.</p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 6: PHENOL REACTIONS */}
      {activeTab === "phenol-reactions" && (
        <div className="space-y-4 sm:space-y-5 max-w-4xl mx-auto w-full">
          <div className="p-3.5 sm:p-5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-3">
            <h4 className="text-sm sm:text-base font-black text-slate-900 flex items-center gap-2">
              <Split className="w-4 h-4 text-emerald-600 shrink-0" />
              Phenol Syntheses (Cumene Process) &amp; Electrophilic Substitutions
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-[10px]">
              <div className="p-2.5 rounded-xl bg-slate-50 border border-slate-200 space-y-1">
                <span className="font-black text-slate-900 uppercase block">Cumene Process (&gt;90% Global)</span>
                <p className="text-slate-800 font-semibold">• Benzene + Propene ──[H₃PO₄]──► Cumene (Isopropylbenzene).</p>
                <p className="text-slate-800 font-semibold">• Air oxidation ──► Cumene Hydroperoxide.</p>
                <p className="text-slate-800 font-bold">• Cleavage with 10% H₂SO₄ ──► <strong>Phenol + Acetone co-product</strong>.</p>
              </div>
              <div className="p-2.5 rounded-xl bg-emerald-50/70 border border-emerald-200 space-y-1">
                <span className="font-black text-emerald-950 uppercase block">Kolbe's &amp; Reimer-Tiemann</span>
                <p className="text-emerald-900 font-semibold">• <strong>Kolbe:</strong> Phenoxide + CO₂ (400 K, 4–7 atm) ──► <strong>Salicylic Acid</strong> (precursor for Aspirin).</p>
                <p className="text-emerald-900 font-semibold">• <strong>Reimer-Tiemann:</strong> Phenol + CHCl₃ + NaOH ──► <strong>Salicylaldehyde</strong> via neutral <strong>:CCl₂</strong> electrophile.</p>
                <p className="text-emerald-900 font-semibold">• <strong>Bromine Water:</strong> 2,4,6-Tribromophenol ↓ (White ppt).</p>
                <p className="text-emerald-900 font-semibold">• <strong>Neutral FeCl₃:</strong> Violet [Fe(OPh)₆]³⁻ complex.</p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 7: ETHERS & HI CLEAVAGE */}
      {activeTab === "ethers-cleavage-calculator" && (
        <div className="space-y-4 sm:space-y-5 max-w-4xl mx-auto w-full">
          <div className="p-3.5 sm:p-5 rounded-2xl bg-white border border-slate-200 shadow-2xs space-y-3">
            <h4 className="text-sm sm:text-base font-black text-slate-900 flex items-center gap-2">
              <FlaskConical className="w-4 h-4 text-purple-600 shrink-0" />
              Williamson Ether Synthesis &amp; Interactive HI Cleavage Simulator
            </h4>
            <div className="p-2.5 rounded-xl bg-slate-50 border border-slate-200 text-[10px] space-y-1">
              <span className="font-black text-slate-900 block">Williamson Synthesis Rule: R-X MUST be 1° or Methyl!</span>
              <p className="text-slate-700 font-semibold">• 1° Halide + Alkoxide ──► Ether via S_N2.</p>
              <p className="text-slate-800 font-bold">• 3° Halide + Alkoxide ──► Alkene (2-Methylpropene) via E2 elimination!</p>
            </div>

            {/* Interactive Ether Cleavage Simulator */}
            <div className="p-3 rounded-xl bg-purple-50 border border-purple-300 space-y-2 text-[10px]">
              <span className="font-black text-purple-950 uppercase tracking-wider block">Interactive HI Ether Cleavage Simulator</span>
              <div className="flex flex-wrap gap-1.5">
                {Object.keys(etherSamples).map((key) => (
                  <button
                    key={key}
                    onClick={() => setSelectedEther(key)}
                    className={`px-2.5 py-1 rounded-lg text-[10px] font-bold border transition-all ${
                      selectedEther === key ? "bg-purple-600 text-white border-purple-600 shadow-xs" : "bg-white text-slate-700 border-slate-200 hover:border-slate-300"
                    }`}
                  >
                    {etherSamples[key].name}
                  </button>
                ))}
              </div>
              <div className="p-3 rounded-lg bg-white border border-purple-300 space-y-1">
                <div className="flex items-center justify-between text-xs">
                  <span className="font-bold text-slate-900">Ether: {etherSamples[selectedEther].name} ({etherSamples[selectedEther].structure})</span>
                  <span className="px-2 py-0.5 rounded text-[10px] font-black uppercase bg-purple-100 text-purple-900">
                    Mechanism: {etherSamples[selectedEther].mechanism}
                  </span>
                </div>
                <div className="p-2 rounded bg-purple-50/70 border border-purple-200 text-xs font-mono font-black text-purple-950">
                  Products: {etherSamples[selectedEther].products}
                </div>
                <p className="text-xs font-semibold text-slate-700 leading-relaxed">{etherSamples[selectedEther].explanation}</p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 8: TRAPS */}
      {activeTab === "traps" && (
        <div className="space-y-4 sm:space-y-5 max-w-4xl mx-auto w-full">
          <div className="p-3.5 sm:p-5 rounded-2xl bg-white border border-amber-300 shadow-2xs space-y-3">
            <h4 className="text-sm sm:text-base font-black text-slate-900 flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0" />
              All 10 High-Yield NEST Alcohols, Phenols &amp; Ethers Misconceptions &amp; Traps
            </h4>
            <div className="space-y-2">
              {alcTraps.map((trap) => {
                const isOpen = activeTrapId === trap.id;
                return (
                  <div key={trap.id} className={`rounded-xl border transition-all ${isOpen ? "bg-amber-50 border-amber-300" : "bg-slate-50 border-slate-200"}`}>
                    <button
                      className="w-full flex items-center justify-between gap-2 p-2.5 text-left"
                      onClick={() => setActiveTrapId(isOpen ? null : trap.id)}
                    >
                      <span className="text-xs font-bold text-slate-800 italic">{trap.trap}</span>
                      <ChevronDown className={`w-3.5 h-3.5 text-slate-500 shrink-0 transition-transform ${isOpen ? "rotate-180" : ""}`} />
                    </button>
                    {isOpen && (
                      <div className="px-2.5 pb-2.5 space-y-1.5">
                        <div className="p-2 rounded-lg bg-white border border-amber-200">
                          <span className="text-[9px] font-black uppercase text-amber-700 tracking-wider block">Chemical Reality</span>
                          <p className="text-xs font-bold text-amber-950">{trap.reality}</p>
                        </div>
                        <div className="p-2 rounded-lg bg-indigo-50 border border-indigo-200">
                          <span className="text-[9px] font-black uppercase text-indigo-700 tracking-wider block">Exam Tip</span>
                          <p className="text-xs font-bold text-indigo-950">{trap.tip}</p>
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}

      {/* TAB 9: MASTER GLOSSARY */}
      {activeTab === "glossary" && (
        <div className="space-y-4 sm:space-y-5 max-w-4xl mx-auto w-full">
          <div className="flex flex-col sm:flex-row items-center gap-3">
            <div className="relative w-full sm:flex-1">
              <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                placeholder="Search alcohols, phenols & ethers terms..."
                value={glossarySearch}
                onChange={(e) => setGlossarySearch(e.target.value)}
                className="w-full pl-9 pr-4 py-2 rounded-xl bg-white border border-slate-200 text-xs font-semibold text-slate-900 focus:outline-none focus:border-blue-500"
              />
            </div>
            <div className="flex flex-wrap gap-1.5 w-full sm:w-auto">
              {["All", "Alcohols & Hydration", "Phenols & Acidity", "Ethers & Mechanisms", "Reagents & Industrial"].map((cat) => (
                <button
                  key={cat}
                  onClick={() => setGlossaryCategory(cat)}
                  className={`px-2.5 py-1 rounded-lg text-[10px] font-bold border transition-all ${
                    glossaryCategory === cat ? "bg-emerald-600 text-white border-emerald-600" : "bg-white text-slate-600 border-slate-200 hover:border-slate-300"
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
            {filteredGlossary.map((item, i) => (
              <div key={i} className="p-3 rounded-xl bg-white border border-slate-200 space-y-1 shadow-2xs">
                <div className="flex items-center justify-between">
                  <h5 className="text-xs font-black text-slate-900">{item.term}</h5>
                  <span className="px-1.5 py-0.5 rounded text-[8px] font-bold bg-slate-100 text-slate-600">{item.category}</span>
                </div>
                <p className="text-xs font-semibold text-slate-700 leading-relaxed">{item.definition}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* TAB 10: NEST 20-Q SELF-TEST */}
      {activeTab === "selftest" && (
        <div className="space-y-4 sm:space-y-5 max-w-4xl mx-auto w-full">
          {score !== null ? (
            <div className="p-4 sm:p-6 rounded-2xl bg-white border border-slate-200 shadow-2xs text-center space-y-3">
              <Award className="w-10 h-10 sm:w-12 sm:h-12 mx-auto text-emerald-500" />
              <h4 className="text-xl sm:text-2xl font-black text-slate-900">Your Score: {score} / {mcqData.length}</h4>
              <p className="text-sm font-semibold text-slate-600">
                {score >= 17 ? "Outstanding! Mastery level for NEST & IChO Alcohols, Phenols & Ethers Module." : score >= 12 ? "Good performance — review incorrect explanations." : "Needs practice — revisit earlier tabs and retake."}
              </p>
              <button onClick={resetSelfTest} className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-slate-900 text-white text-xs font-black hover:bg-slate-700 transition-all">
                <RotateCcw className="w-3.5 h-3.5" /> Retake Assessment
              </button>
            </div>
          ) : (
            <>
              <div className="flex flex-col sm:flex-row items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-black text-slate-500 uppercase tracking-wide">Filter:</span>
                  {(["ALL", "A", "B"] as const).map((part) => (
                    <button
                      key={part}
                      onClick={() => setTestPartFilter(part)}
                      className={`px-2 py-0.5 rounded text-[10px] font-black border transition-all ${
                        testPartFilter === part ? "bg-emerald-600 text-white border-emerald-600" : "bg-white text-slate-600 border-slate-200"
                      }`}
                    >
                      {part === "ALL" ? "All 20 Questions" : part === "A" ? "Part A (Single MCQ)" : "Part B (Multi MSQ)"}
                    </button>
                  ))}
                </div>
                <div className="flex items-center gap-2 w-full sm:w-auto">
                  <div className="flex-1 sm:w-36 h-2 rounded-full bg-slate-200 overflow-hidden">
                    <div className="h-full rounded-full bg-emerald-500 transition-all duration-500" style={{ width: `${((currentQ + 1) / mcqData.length) * 100}%` }} />
                  </div>
                  <span className="text-[10px] font-black text-slate-700">Q{currentQ + 1} of {mcqData.length}</span>
                </div>
              </div>

              <div className="p-3.5 sm:p-6 rounded-2xl sm:rounded-3xl bg-white border border-slate-200 shadow-2xs space-y-4">
                <div className="flex items-start gap-2">
                  <span className="w-6 h-6 rounded-full bg-emerald-600 text-white text-[10px] font-black flex items-center justify-center shrink-0 mt-0.5">
                    {currentMCQ.id}
                  </span>
                  <div className="space-y-1">
                    <div className="flex items-center gap-1.5">
                      <span className="px-1.5 py-0.5 rounded text-[8px] font-black uppercase tracking-wider bg-slate-100 text-slate-700">
                        Part {currentMCQ.part}
                      </span>
                      <span className={`px-1.5 py-0.5 rounded text-[8px] font-black uppercase tracking-wider ${
                        currentMCQ.type === "multi" ? "bg-purple-100 text-purple-800" : "bg-emerald-100 text-emerald-800"
                      }`}>
                        {currentMCQ.type === "multi" ? "Multi-Select MSQ (One or more correct)" : "Single-Correct MCQ"}
                      </span>
                    </div>
                    <p className="text-xs sm:text-sm font-bold text-slate-900 leading-relaxed">{currentMCQ.question}</p>
                  </div>
                </div>

                <div className="space-y-2">
                  {currentMCQ.options.map((opt) => {
                    const isSelected = (selectedAnswers[currentQ] || []).includes(opt.key);
                    const isSubmitted = submitted[currentQ];
                    const isCorrect = currentMCQ.correctKeys.includes(opt.key);

                    let bg = "bg-white border-slate-200 hover:border-slate-300";
                    if (isSubmitted) {
                      if (isCorrect) bg = "bg-emerald-50 border-emerald-400";
                      else if (isSelected && !isCorrect) bg = "bg-rose-50 border-rose-400";
                    } else if (isSelected) {
                      bg = "bg-emerald-50 border-emerald-400";
                    }

                    return (
                      <button key={opt.key} onClick={() => toggleAnswer(currentQ, opt.key, currentMCQ.type)} className={`w-full flex items-start gap-2.5 p-2.5 rounded-xl border-2 text-left transition-all ${bg}`}>
                        <span className={`w-5 h-5 rounded shrink-0 border-2 flex items-center justify-center text-[10px] font-black transition-all ${
                          isSubmitted && isCorrect ? "bg-emerald-600 border-emerald-600 text-white" : isSubmitted && isSelected && !isCorrect ? "bg-rose-600 border-rose-600 text-white" : isSelected ? "bg-emerald-600 border-emerald-600 text-white" : "border-slate-300 text-slate-500"
                        }`}>
                          {isSubmitted && isCorrect ? "✓" : isSubmitted && isSelected && !isCorrect ? "✗" : opt.key}
                        </span>
                        <span className="text-xs font-semibold text-slate-800 leading-relaxed">{opt.text}</span>
                      </button>
                    );
                  })}
                </div>

                {submitted[currentQ] && (
                  <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 space-y-1">
                    <div className="flex items-center gap-1.5">
                      <BookOpen className="w-3.5 h-3.5 text-emerald-600 shrink-0" />
                      <span className="text-[9px] font-black uppercase tracking-wider text-emerald-700">Detailed Solution &amp; Mechanistic Explanation</span>
                    </div>
                    <p className="text-xs font-semibold text-slate-800 leading-relaxed">{currentMCQ.explanation}</p>
                  </div>
                )}

                <div className="flex items-center gap-2 flex-wrap">
                  {!submitted[currentQ] ? (
                    <button onClick={() => submitAnswer(currentQ)} disabled={!(selectedAnswers[currentQ]?.length)} className="px-4 py-2 rounded-xl bg-emerald-600 text-white text-xs font-black hover:bg-emerald-700 disabled:opacity-40 disabled:cursor-not-allowed transition-all">Submit Answer</button>
                  ) : null}
                  {currentQ < mcqData.length - 1 && (
                    <button onClick={() => setCurrentQ((q) => q + 1)} className="px-4 py-2 rounded-xl bg-slate-900 text-white text-xs font-black hover:bg-slate-700 transition-all flex items-center gap-1.5">
                      Next Question <ChevronRight className="w-3.5 h-3.5" />
                    </button>
                  )}
                  {currentQ === mcqData.length - 1 && submitted[currentQ] && (
                    <button onClick={computeScore} className="px-4 py-2 rounded-xl bg-emerald-600 text-white text-xs font-black hover:bg-emerald-700 transition-all flex items-center gap-1.5">
                      <Award className="w-3.5 h-3.5" /> See Final Score
                    </button>
                  )}
                  {currentQ > 0 && (
                    <button onClick={() => setCurrentQ((q) => q - 1)} className="px-3 py-2 rounded-xl bg-slate-100 text-slate-700 text-xs font-black hover:bg-slate-200 transition-all">Back</button>
                  )}
                </div>
              </div>

              {/* Question Navigator */}
              <div className="flex flex-wrap gap-1.5">
                {mcqData.map((q, i) => {
                  const isDone = submitted[i];
                  const sel = selectedAnswers[i] || [];
                  const isCorrect = isDone && sel.length === q.correctKeys.length && q.correctKeys.every(k => sel.includes(k));
                  return (
                    <button key={i} onClick={() => setCurrentQ(i)} className={`w-7 h-7 rounded-lg text-[10px] font-black border transition-all ${
                      i === currentQ ? "bg-emerald-600 text-white border-emerald-600" : isDone ? isCorrect ? "bg-emerald-100 text-emerald-800 border-emerald-300" : "bg-rose-100 text-rose-800 border-rose-300" : "bg-white text-slate-600 border-slate-200 hover:border-slate-400"
                    }`}>{i + 1}</button>
                  );
                })}
              </div>
            </>
          )}
        </div>
      )}
    </div>
  );
};

export default AlcoholsPhenolsEthersDiagram;
