import json
import os

def create_mock(mock_id, title, difficulty):
    subjects = ["Physics", "Chemistry", "Biology", "Mathematics"]
    
    # Subject topic banks
    phy_topics = [
        ("Kinematics & Projectile Motion", "A particle moves along a straight line such that its velocity $v$ at displacement $x$ is given by $v^2 = 144 - 9x^2$. The particle executes simple harmonic motion. Its angular frequency $\\omega$ and maximum displacement are:", [("$\\omega = 3\\text{ rad/s}, A = 4\\text{ m}$", True, "Compare $v^2 = \\omega^2(A^2 - x^2)$ with $v^2 = 9(16 - x^2)$. Thus $\\omega = 3\\text{ rad/s}$ and $A = 4\\text{ m}$."), ("$\\omega = 9\\text{ rad/s}, A = 12\\text{ m}$", False, "Incorrect."), ("$\\omega = 12\\text{ rad/s}, A = 3\\text{ m}$", False, "Incorrect."), ("$\\omega = 4\\text{ rad/s}, A = 3\\text{ m}$", False, "Incorrect.")]),
        ("Work, Energy & Power", "A block of mass $m = 2\\text{ kg}$ is attached to a spring of stiffness $k = 200\\text{ N/m}$. If the block is released from rest when the spring is compressed by $0.2\\text{ m}$, its speed as it passes through the natural equilibrium position on a frictionless table is:", [("$2.0\\text{ m/s}$", True, "By conservation of mechanical energy: $\\frac{1}{2}kx^2 = \\frac{1}{2}mv^2 \\implies v = x\\sqrt{k/m} = 0.2\\sqrt{200/2} = 2.0\\text{ m/s}$."), ("$1.41\\text{ m/s}$", False, "Incorrect."), ("$4.0\\text{ m/s}$", False, "Incorrect."), ("$0.5\\text{ m/s}$", False, "Incorrect.")]),
        ("Rotational Dynamics", "A uniform solid cylinder and a thin spherical shell of equal mass $M$ and equal radius $R$ roll down an incline of angle $\\theta$ without slipping from rest. The ratio of their linear accelerations $a_{\\text{cyl}} / a_{\\text{sph}}$ is:", [("$\\frac{25}{24}$", True, "$a = \\frac{g\\sin\\theta}{1 + I/(MR^2)}$. For solid cylinder $I/(MR^2) = 1/2 \\implies a_{\\text{cyl}} = \\frac{2}{3}g\\sin\\theta$. For thin spherical shell $I/(MR^2) = 2/3 \\implies a_{\\text{sph}} = \\frac{3}{5}g\\sin\\theta$. Ratio = $(2/3) / (3/5) = 10/9$ or strictly $\\frac{10}{9}$."), ("$\\frac{10}{9}$", True, "For cylinder $a_1 = \\frac{2}{3}g\\sin\\theta$; for thin shell $a_2 = \\frac{3}{5}g\\sin\\theta$, giving ratio $\\frac{10}{9}$."), ("$\\frac{9}{10}$", False, "Incorrect."), ("$\\frac{7}{5}$", False, "Incorrect.")]),
        ("Gravitation & Orbital Mechanics", "A satellite orbits the Earth at height $h = R$ above the Earth's surface ($R = \\text{radius of Earth}$). If the satellite is to escape to infinity, the percentage increase in its orbital kinetic energy must be:", [("$100\\%$", True, "Orbital speed $v_0 = \\sqrt{GM/(2R)}$, Escape speed $v_e = \\sqrt{2GM/(2R)} = \\sqrt{2}v_0$. Kinetic energy ratio $K_e/K_0 = (v_e/v_0)^2 = 2$. Hence $\\Delta K / K_0 = 100\\%$."), ("$41.4\\%$", False, "This is the increase in speed, not kinetic energy."), ("$50\\%$", False, "Incorrect."), ("$200\\%$", False, "Incorrect.")]),
        ("Thermodynamics & Heat Engines", "An ideal monoatomic gas undergoes a cyclic process consisting of an isobaric expansion ($1 \\to 2$), an isochoric cooling ($2 \\to 3$), and an isothermal compression ($3 \\to 1$). The efficiency of this heat engine depends on:", [("The expansion ratio and heat capacities", True, "Efficiency $\\eta = W_{\\text{net}} / Q_{\\text{in}}$ which is derived from the temperature and volume ratios of the cycle."), ("Only the extreme temperatures", False, "This is only true for a Carnot cycle."), ("Only the universal gas constant", False, "Incorrect."), ("Zero efficiency", False, "Incorrect.")]),
        ("Electrostatics & Gauss's Law", "A non-conducting sphere of radius $R$ carries a non-uniform volume charge density $\\rho(r) = \\rho_0 (r/R)$ for $r \\le R$. The electric field at a distance $r < R$ from the center is proportional to:", [("$r^2$", True, "$q_{\\text{enc}} = \\int_0^r 4\\pi r'^2 (\\rho_0 r'/R) dr' = \\frac{\\pi \\rho_0 r^4}{R}$. By Gauss's law $E(4\\pi r^2) = q_{\\text{enc}}/\\epsilon_0 \\implies E \\propto r^2$."), ("$r$", False, "Only true for uniform charge density."), ("$r^3$", False, "Incorrect."), ("$r^{-2}$", False, "True only outside the sphere.")]),
        ("Current Electricity", "In a balanced Wheatstone bridge, the four arm resistances are $P = 10\\,\\Omega$, $Q = 20\\,\\Omega$, $R = 30\\,\\Omega$, and $S = 60\\,\\Omega$. If the galvanometer and battery are interchanged, the bridge will:", [("Remain balanced", True, "By the reciprocity theorem for linear resistive networks, interchanging the source and detector does not affect the balance condition $PS = QR$ ($10 \\times 60 = 20 \\times 30$)."), ("Become unbalanced", False, "Incorrect."), ("Have zero current through all resistors", False, "Incorrect."), ("Burn the galvanometer", False, "Incorrect.")]),
        ("Magnetic Effects of Current", "A long cylindrical conductor of radius $a$ carries a uniform current $I$ along its length. The magnetic field $B(r)$ as a function of radial distance $r$ inside the conductor ($r < a$) is:", [("$\\frac{\\mu_0 I r}{2\\pi a^2}$", True, "By Ampere's law: $\\oint B \\cdot dl = B(2\\pi r) = \\mu_0 I_{\\text{enc}} = \\mu_0 I \\frac{\\pi r^2}{\\pi a^2} \\implies B = \\frac{\\mu_0 I r}{2\\pi a^2}$."), ("$\\frac{\\mu_0 I}{2\\pi r}$", False, "This is for $r \\ge a$."), ("$\\frac{\\mu_0 I a}{2\\pi r^2}$", False, "Incorrect."), ("Zero", False, "Incorrect.")]),
        ("Electromagnetic Induction", "A circular coil of $N$ turns and radius $R$ rotates with angular speed $\\omega$ in a uniform magnetic field $B$ about an axis perpendicular to the field. The peak induced electromotive force (EMF) is:", [("$N B \\pi R^2 \\omega$", True, "Flux $\\Phi = N B A \\cos(\\omega t)$. Induced EMF $\\mathcal{E} = -d\\Phi/dt = N B (\\pi R^2) \\omega \\sin(\\omega t)$. Peak value is $N B \\pi R^2 \\omega$."), ("$\\frac{N B \\pi R^2}{\\omega}$", False, "Incorrect."), ("$2 N B \\pi R^2 \\omega$", False, "Incorrect."), ("Zero", False, "Incorrect.")]),
        ("Ray Optics & Refraction", "A light ray enters a glass slab of refractive index $\\mu = \\sqrt{2}$ from air at an incident angle of $45^\\circ$. The lateral shift produced across a slab thickness $t = 10\\text{ cm}$ is:", [("$\\frac{10}{\\sqrt{2}}\\left(1 - \\frac{1}{\\sqrt{3}}\\right)\\text{ cm}$", True, "Lateral shift $\\delta = t \\frac{\\sin(i - r)}{\\cos r}$. By Snell's Law: $1 \\sin 45^\\circ = \\sqrt{2} \\sin r \\implies \\sin r = 1/2 \\implies r = 30^\\circ$. Thus $\\delta = 10 \\frac{\\sin 15^\\circ}{\\cos 30^\\circ}$."), ("$5\\sqrt{2}\\text{ cm}$", False, "Incorrect."), ("$10\\text{ cm}$", False, "Incorrect."), ("Zero", False, "Incorrect.")]),
        ("Wave Optics & Interference", "In a standard Young's double-slit experiment with monochromatic light of wavelength $\\lambda$, the slit separation is $d$ and screen distance is $D$. If the central bright fringe is shifted by the thickness $t$ of a thin transparent mica sheet of refractive index $\\mu$ placed over one slit, the optical path difference introduced is:", [("$(\\mu - 1)t$", True, "The optical path through the mica sheet is $\\mu t$, while in air it is $t$. The net path difference is $(\\mu - 1)t$."), ("$\\mu t$", False, "Incorrect."), ("$(\\mu + 1)t$", False, "Incorrect."), ("$\\frac{t}{\\mu - 1}$", False, "Incorrect.")]),
        ("Dual Nature of Radiation & Matter", "Photons of energy $4.5\\text{ eV}$ strike a metal surface with work function $\\Phi = 2.5\\text{ eV}$. The stopping potential $V_0$ required to retard all emitted photoelectrons is:", [("$2.0\\text{ V}$", True, "Einstein's photoelectric equation: $e V_0 = h\\nu - \\Phi = 4.5\\text{ eV} - 2.5\\text{ eV} = 2.0\\text{ eV} \\implies V_0 = 2.0\\text{ V}$."), ("$7.0\\text{ V}$", False, "Incorrect."), ("$4.5\\text{ V}$", False, "Incorrect."), ("$1.8\\text{ V}$", False, "Incorrect.")]),
        ("Atomic Physics & Bohr Model", "In the hydrogen atom spectrum, the ratio of the longest wavelength in the Lyman series to the longest wavelength in the Balmer series is:", [("$\\frac{5}{27}$", True, "Longest Lyman ($2 \\to 1$): $1/\\lambda_L = R_H(1 - 1/4) = 3R_H/4$. Longest Balmer ($3 \\to 2$): $1/\\lambda_B = R_H(1/4 - 1/9) = 5R_H/36$. Ratio $\\lambda_L/\\lambda_B = (4/3R_H) / (36/5R_H) = 5/27$."), ("$\\frac{27}{5}$", False, "Incorrect."), ("$\\frac{4}{9}$", False, "Incorrect."), ("$\\frac{9}{4}$", False, "Incorrect.")]),
        ("Nuclear Physics & Radioactivity", "A radioactive sample has a half-life of $T_{1/2} = 10\\text{ days}$. The fraction of the original active nuclei remaining undecayed after $40\\text{ days}$ is:", [("$\\frac{1}{16}$", True, "Number of half-lives $n = 40/10 = 4$. Remaining fraction = $(1/2)^4 = 1/16 = 6.25\\%$."), ("$\\frac{1}{8}$", False, "Incorrect."), ("$\\frac{1}{32}$", False, "Incorrect."), ("$\\frac{1}{4}$", False, "Incorrect.")]),
        ("Semiconductor Electronics", "In a reverse-biased p-n junction diode, the width of the depletion region and the barrier potential height respectively:", [("Increase and Increase", True, "Reverse bias opposes majority carrier diffusion and aids minority drift, widening the depletion region and elevating the effective potential barrier ($V_0 + V_R$)."), ("Decrease and Decrease", False, "This happens in forward bias."), ("Increase and Decrease", False, "Incorrect."), ("Remain unchanged", False, "Incorrect.")]),
        ("Oscillations & Waves", "A simple pendulum of length $L$ has period $T$ on Earth. If it is placed in an elevator accelerating upwards with acceleration $a = g/3$, the new period becomes:", [("$\\frac{\\sqrt{3}}{2}T$", True, "Effective gravity $g_{\\text{eff}} = g + a = 4g/3$. New period $T' = 2\\pi \\sqrt{L/(4g/3)} = \\frac{\\sqrt{3}}{2} T$."), ("$\\frac{2}{\\sqrt{3}}T$", False, "Incorrect."), ("$\\sqrt{3}T$", False, "Incorrect."), ("$\\frac{1}{2}T$", False, "Incorrect.")]),
        ("Fluid Mechanics & Bernoulli's Theorem", "Water flows through a horizontal pipe of non-uniform cross-section. At point $A$ the velocity is $2\\text{ m/s}$ and pressure is $200\\text{ kPa}$. At point $B$ where the area is half that of $A$, the velocity and pressure are ($g = 10\\text{ m/s}^2, \\rho = 1000\\text{ kg/m}^3$):", [("$v_B = 4\\text{ m/s},\\, P_B = 194\\text{ kPa}$", True, "By continuity: $A_A v_A = A_B v_B \\implies v_B = 2(2) = 4\\text{ m/s}$. By Bernoulli: $P_A + \\frac{1}{2}\\rho v_A^2 = P_B + \\frac{1}{2}\\rho v_B^2 \\implies P_B = 200\\text{ kPa} + \\frac{1}{2}(1000)(4 - 16) = 194\\text{ kPa}$."), ("$v_B = 4\\text{ m/s},\\, P_B = 206\\text{ kPa}$", False, "Incorrect."), ("$v_B = 1\\text{ m/s},\\, P_B = 203\\text{ kPa}$", False, "Incorrect."), ("$v_B = 8\\text{ m/s},\\, P_B = 150\\text{ kPa}$", False, "Incorrect.")]),
        ("Thermodynamic Processes", "An ideal gas undergoes an adiabatic expansion where its volume is doubled ($V_2 = 2V_1$). If the ratio of specific heats is $\\gamma = 1.5$, the ratio of final temperature to initial temperature $T_2/T_1$ is:", [("$\\frac{1}{\\sqrt{2}}$", True, "For an adiabatic process: $T V^{\\gamma - 1} = \\text{constant} \\implies T_2/T_1 = (V_1/V_2)^{\\gamma - 1} = (1/2)^{0.5} = 1/\\sqrt{2}$."), ("$\\sqrt{2}$", False, "Incorrect."), ("$0.5$", False, "Incorrect."), ("$2.0$", False, "Incorrect.")]),
        ("Capacitance & Dielectrics", "A parallel plate capacitor of capacitance $C_0$ is connected to a battery of voltage $V$. While keeping the battery connected, a dielectric slab of constant $K = 4$ is inserted to completely fill the gap. The stored electrostatic energy becomes:", [("$4 U_0$", True, "With battery connected, voltage $V$ remains constant. Capacitance $C = K C_0 = 4 C_0$. Energy $U = \\frac{1}{2} C V^2 = 4 \\times (\\frac{1}{2} C_0 V^2) = 4 U_0$."), ("$\\frac{1}{4} U_0$", False, "This is when the battery is disconnected."), ("$16 U_0$", False, "Incorrect."), ("$U_0$", False, "Incorrect.")]),
        ("Alternating Current Circuits", "In a series LCR circuit with $R = 30\\,\\Omega$, $X_L = 80\\,\\Omega$, and $X_C = 40\\,\\Omega$ connected to an AC source $V(t) = 200\\sin(\\omega t)$, the power factor of the circuit is:", [("$0.60$", True, "Impedance $Z = \\sqrt{R^2 + (X_L - X_C)^2} = \\sqrt{30^2 + 40^2} = 50\\,\\Omega$. Power factor $\\cos\\phi = R/Z = 30/50 = 0.60$ (lagging)."), ("$0.80$", False, "Incorrect."), ("$1.00$", False, "Incorrect."), ("$0.50$", False, "Incorrect.")])
    ]

    chem_topics = [
        ("Some Basic Concepts of Chemistry", "The number of water molecules present in a drop of water of volume $0.05\\text{ mL}$ (density $\\rho = 1.0\\text{ g/mL}$) is approximately ($N_A = 6.022 \\times 10^{23}$):", [("$1.67 \\times 10^{21}$", True, "Mass $m = 0.05\\text{ g}$. Moles $n = 0.05/18 = 2.78 \\times 10^{-3}\\text{ mol}$. Molecules = $n N_A = 1.67 \\times 10^{21}$."), ("$6.02 \\times 10^{22}$", False, "Incorrect."), ("$3.01 \\times 10^{21}$", False, "Incorrect."), ("$1.80 \\times 10^{20}$", False, "Incorrect.")]),
        ("Structure of Atom", "The de Broglie wavelength associated with an electron accelerated through a potential difference of $100\\text{ V}$ is approximately:", [("$0.123\\text{ nm}$", True, "$\\lambda = \\frac{1.227}{\\sqrt{V}}\\text{ nm} = \\frac{1.227}{10} = 0.1227\\text{ nm} \\approx 0.123\\text{ nm}$."), ("$1.23\\text{ nm}$", False, "Incorrect."), ("$0.012\\text{ nm}$", False, "Incorrect."), ("$12.3\\text{ nm}$", False, "Incorrect.")]),
        ("Periodic Classification & Periodicity", "The correct order of second ionization enthalpy ($IE_2$) among the following period-2 elements is:", [("$\\text{Li} > \\text{O} > \\text{F} > \\text{N}$", True, "$\\text{Li}^+$ attains stable noble gas configuration ($1s^2$), giving it the highest $IE_2$. $\\text{O}^+$ ($2p^3$) is half-filled and exceeds $\\text{F}^+$ ($2p^4$) and $\\text{N}^+$ ($2p^2$)."), ("$\\text{O} > \\text{F} > \\text{N} > \\text{Li}$", False, "Incorrect."), ("$\\text{Li} > \\text{F} > \\text{O} > \\text{N}$", False, "Incorrect."), ("$\\text{F} > \\text{O} > \\text{N} > \\text{Li}$", False, "Incorrect.")]),
        ("Chemical Bonding & Molecular Structure", "According to VSEPR theory, the geometry and shape of $\\text{XeF}_4$ are respectively:", [("Octahedral and Square Planar", True, "$\\text{Xe}$ has 8 valence electrons + 4 bonds = 12 electrons = 6 electron pairs (4 bonding + 2 lone pairs). Electron geometry is Octahedral, molecular shape is Square Planar."), ("Tetrahedral and Square Planar", False, "Incorrect."), ("Octahedral and See-Saw", False, "Incorrect."), ("Trigonal Bipyramidal and T-Shaped", False, "Incorrect.")]),
        ("Chemical Thermodynamics", "For the reaction $2\\text{SO}_2(g) + \\text{O}_2(g) \\rightleftharpoons 2\\text{SO}_3(g)$, $\\Delta H^\circ = -198\\text{ kJ/mol}$. The reaction is spontaneous at:", [("Low temperatures only", True, "$\\Delta H < 0$ and $\\Delta S < 0$ (moles decrease from 3 to 2). $\\Delta G = \\Delta H - T\\Delta S < 0$ when $|T\\Delta S| < |\\Delta H|$, meaning at low temperatures."), ("High temperatures only", False, "At high $T$, $-T\\Delta S$ dominates making $\\Delta G > 0$."), ("All temperatures", False, "Incorrect."), ("No temperature", False, "Incorrect.")]),
        ("Chemical Equilibrium", "For the equilibrium $\\text{N}_2\\text{O}_4(g) \\rightleftharpoons 2\\text{NO}_2(g)$, the degree of dissociation $\\alpha$ is related to vapor densities $D$ (initial) and $d$ (equilibrium) by:", [("$\\alpha = \\frac{D - d}{d}$", True, "Total moles at equilibrium = $1 + \\alpha$. Since $D/d = 1 + (n-1)\\alpha$ and here $n = 2$, we have $D/d = 1 + \\alpha \\implies \\alpha = \\frac{D - d}{d}$."), ("$\\alpha = \\frac{d - D}{D}$", False, "Incorrect."), ("$\\alpha = \\frac{D - d}{2d}$", False, "Incorrect."), ("$\\alpha = \\frac{2(D - d)}{d}$", False, "Incorrect.")]),
        ("Ionic Equilibrium", "The pH of a buffer solution prepared by mixing $0.1\\text{ M } \\text{CH}_3\\text{COOH}$ ($pK_a = 4.74$) and $0.2\\text{ M } \\text{CH}_3\\text{COONa}$ is:", [("$5.04$", True, "Henderson-Hasselbalch: $\\text{pH} = pK_a + \\log\\frac{[\\text{Salt}]}{[\\text{Acid}]} = 4.74 + \\log\\frac{0.2}{0.1} = 4.74 + 0.3010 = 5.04$."), ("$4.44$", False, "Incorrect."), ("$4.74$", False, "Incorrect."), ("$5.34$", False, "Incorrect.")]),
        ("Redox Reactions & Electrochemistry", "The standard reduction potentials are: $E^\\circ(\\text{Zn}^{2+}/\\text{Zn}) = -0.76\\text{ V}$ and $E^\\circ(\\text{Cu}^{2+}/\\text{Cu}) = +0.34\\text{ V}$. The standard EMF of the Daniell cell and its equilibrium constant $K$ at $298\\text{ K}$ are:", [("$E^\\circ = 1.10\\text{ V},\\, K \\approx 10^{37}$", True, "$E^\\circ_{\\text{cell}} = E^\\circ_{\\text{cathode}} - E^\\circ_{\\text{anode}} = 0.34 - (-0.76) = 1.10\\text{ V}$. $\\log K = \\frac{n E^\\circ}{0.0591} = \\frac{2 \\times 1.10}{0.0591} \\approx 37.2 \\implies K \\approx 10^{37}$."), ("$E^\\circ = 0.42\\text{ V},\\, K \\approx 10^{14}$", False, "Incorrect."), ("$E^\\circ = 1.10\\text{ V},\\, K \\approx 10^{18}$", False, "Incorrect."), ("$E^\\circ = -1.10\\text{ V},\\, K \\approx 10^{-37}$", False, "Incorrect.")]),
        ("Chemical Kinetics", "For a first-order reaction $A \\to \\text{Products}$, the time required for $99.9\\%$ completion is related to its half-life $t_{1/2}$ by:", [("$t_{99.9\\%} \\approx 10\\, t_{1/2}$", True, "$t_{99.9\\%} = \\frac{2.303}{k} \\log\\frac{100}{0.1} = \\frac{2.303 \\times 3}{k} = \\frac{6.909}{k}$. Since $t_{1/2} = 0.693/k$, $t_{99.9\\%}/t_{1/2} \\approx 6.909/0.693 = 9.97 \\approx 10$."), ("$t_{99.9\\%} \\approx 3\\, t_{1/2}$", False, "Incorrect."), ("$t_{99.9\\%} \\approx 5\\, t_{1/2}$", False, "Incorrect."), ("$t_{99.9\\%} \\approx 20\\, t_{1/2}$", False, "Incorrect.")]),
        ("Solutions & Colligative Properties", "The Van 't Hoff factor $i$ for a $0.05\\text{ m}$ aqueous solution of $\\text{K}_3[\\text{Fe}(\\text{CN})_6]$ with degree of dissociation $\\alpha = 0.80$ is:", [("$3.40$", True, "$\\text{K}_3[\\text{Fe}(\\text{CN})_6] \\to 3\\text{K}^+ + [\\text{Fe}(\\text{CN})_6]^{3-}$ ($n = 4$). $i = 1 + (n - 1)\\alpha = 1 + (4 - 1)(0.80) = 1 + 2.40 = 3.40$."), ("$4.00$", False, "Incorrect."), ("$2.60$", False, "Incorrect."), ("$3.00$", False, "Incorrect.")]),
        ("p-Block Elements (Group 15-18)", "Which of the following oxoacids of phosphorus contains $\\text{P}-\\text{H}$ bonds and behaves as a strong reducing agent?", [("$\\text{H}_3\\text{PO}_2$ (Hypophosphorous acid)", True, "$\\text{H}_3\\text{PO}_2$ has one $\\text{P}=\\text{O}$, one $\\text{P}-\\text{OH}$, and two $\\text{P}-\\text{H}$ bonds, conferring powerful reducing character."), ("$\\text{H}_3\\text{PO}_4$ (Orthophosphoric acid)", False, "Has zero P-H bonds."), ("$\\text{H}_4\\text{P}_2\\text{O}_7$ (Pyrophosphoric acid)", False, "Has zero P-H bonds."), ("$\\text{HPO}_3$ (Metaphosphoric acid)", False, "Incorrect.")]),
        ("d- and f-Block Elements", "The magnetic moment (spin-only) of a divalent transition metal ion $\\text{M}^{2+}$ ($Z = 25$) in aqueous solution is:", [("$5.92\\text{ BM}$", True, "$\\text{Mn}^{2+}$ has $3d^5$ configuration ($n = 5$ unpaired electrons). $\\mu = \\sqrt{n(n+2)} = \\sqrt{5(7)} = \\sqrt{35} \\approx 5.92\\text{ BM}$."), ("$4.90\\text{ BM}$", False, "For $n = 4$ ($3d^6$ or $3d^4$)."), ("$3.87\\text{ BM}$", False, "For $n = 3$."), ("$1.73\\text{ BM}$", False, "For $n = 1$.")]),
        ("Coordination Compounds", "According to Crystal Field Theory, the crystal field stabilization energy (CFSE) for a high-spin $d^6$ octahedral complex is:", [("$-0.4\\Delta_o$", True, "High spin $d^6$: $t_{2g}^4 e_g^2$. $\\text{CFSE} = 4(-0.4\\Delta_o) + 2(+0.6\\Delta_o) = -1.6\\Delta_o + 1.2\\Delta_o = -0.4\\Delta_o$."), ("$-2.4\\Delta_o + 2P$", False, "This is low spin $d^6$."), ("$-0.6\\Delta_o$", False, "Incorrect."), ("$0.0$", False, "Incorrect.")]),
        ("General Organic Chemistry (GOC)", "The correct order of stability among the following carbocations is:", [("$\\text{Tropylium} > \\text{Triphenylmethyl} > \\text{tert-Butyl} > \\text{Isopropyl}$", True, "Tropylium ion is aromatic ($6\\pi$ electrons with complete resonance delocalization across 7 carbons), making it exceptionally stable."), ("$\\text{Triphenylmethyl} > \\text{Tropylium} > \\text{tert-Butyl} > \\text{Isopropyl}$", False, "Incorrect."), ("$\\text{tert-Butyl} > \\text{Tropylium} > \\text{Isopropyl} > \\text{Triphenylmethyl}$", False, "Incorrect."), ("$\\text{Isopropyl} > \\text{tert-Butyl} > \\text{Tropylium} > \\text{Triphenylmethyl}$", False, "Incorrect.")]),
        ("Hydrocarbons & Reaction Mechanisms", "Addition of $\\text{HBr}$ to 3,3-dimethylbut-1-ene in the presence of peroxide gives predominantly:", [("3-Bromo-2,2-dimethylbutane", True, "Peroxide anti-Markovnikov addition proceeds via a secondary free radical intermediate which undergoes negligible rearrangement compared to carbocations, yielding 1-bromo-3,3-dimethylbutane or terminal adduct."), ("1-Bromo-3,3-dimethylbutane", True, "Anti-Markovnikov addition of HBr in the presence of peroxide adds Br to the terminal carbon without carbocation rearrangement, yielding 1-bromo-3,3-dimethylbutane."), ("2-Bromo-2,3-dimethylbutane", False, "This is formed via carbocation rearrangement in the absence of peroxides."), ("2,3-Dibromo-2,3-dimethylbutane", False, "Incorrect.")]),
        ("Haloalkanes and Haloarenes", "Which alkyl halide reacts fastest via the $\\text{S}_\\text{N}1$ mechanism upon solvolysis in aqueous ethanol?", [("$\\text{tert-Butyl iodide } (\\text{CH}_3)_3\\text{C-I}$", True, "Forms a stable tertiary carbocation and iodide ($\\text{I}^-$) is the best leaving group due to lowest bond dissociation energy and large ionic radius."), ("$(\\text{CH}_3)_3\\text{C-Cl}$", False, "Cl is a poorer leaving group than I."), ("$\\text{CH}_3\\text{CH}_2\\text{-I}$", False, "Primary alkyl halide undergoes SN2."), ("$(\\text{CH}_3)_2\\text{CH-Br}$", False, "Secondary alkyl halide is slower than tertiary.")]),
        ("Alcohols, Phenols and Ethers", "When anisole is heated with concentrated hydroiodic acid ($\\text{HI}$), the major products formed are:", [("Phenol and Iodomethane", True, "The phenoxide oxygen is resonance-stabilized with the benzene ring (partial double bond character). Cleavage occurs at the alkyl-oxygen bond via SN2 by iodide on the methyl group, yielding phenol + CH3I."), ("Iodobenzene and Methanol", False, "Aryl-oxygen bond has partial double bond character and cannot be cleaved under standard conditions."), ("Benzene and Methyl iodide", False, "Incorrect."), ("o-Iodoanisole", False, "Incorrect.")]),
        ("Aldehydes, Ketones & Carboxylic Acids", "Aldol condensation does NOT occur in which of the following aldehydes upon treatment with dilute $\\text{NaOH}$?", [("2,2-Dimethylpropanal (Pivalaldehyde)", True, "Pivalaldehyde $((\\text{CH}_3)_3\\text{C-CHO})$ lacks $\\alpha$-hydrogen atoms, hence cannot undergo aldol condensation; it undergoes Cannizzaro reaction instead."), ("Acetaldehyde", False, "Has 3 alpha hydrogens."), ("Propionaldehyde", False, "Has 2 alpha hydrogens."), ("Phenylethanal", False, "Has 2 alpha hydrogens.")]),
        ("Amines & Diazonium Salts", "The Hinsberg test distinguishes primary, secondary, and tertiary amines using benzenesulfonyl chloride. A secondary amine reacts to give a product that:", [("Is insoluble in aqueous $\\text{KOH}$", True, "Secondary amines form N,N-dialkylbenzenesulfonamides which lack an acidic hydrogen on the nitrogen, hence are insoluble in alkali."), ("Is soluble in aqueous $\\text{KOH}$", False, "This is for primary amines."), ("Does not react at all", False, "This is for tertiary amines."), ("Forms an explosive gas", False, "Incorrect.")]),
        ("Biomolecules & Polymers", "In DNA double helix, the two polynucleotide chains are held together by hydrogen bonds between nitrogenous bases. The number of hydrogen bonds between Guanine and Cytosine is:", [("3 Hydrogen Bonds", True, "Guanine pairs with Cytosine via 3 hydrogen bonds ($G \\equiv C$), while Adenine pairs with Thymine via 2 hydrogen bonds ($A = T$)."), ("2 Hydrogen Bonds", False, "This is for A=T pair."), ("1 Hydrogen Bond", False, "Incorrect."), ("4 Hydrogen Bonds", False, "Incorrect.")])
    ]

    bio_topics = [
        ("The Living World & Taxonomy", "Which of the following taxonomic categories represents the highest rank with the least number of shared common characteristics?", [("Kingdom", True, "As we go from species to kingdom, the number of common characteristics decreases while generality increases."), ("Species", False, "Species has the highest number of shared traits."), ("Genus", False, "Incorrect."), ("Family", False, "Incorrect.")]),
        ("Biological Classification", "Methanogenic archaebacteria differ fundamentally from eubacteria in possessing:", [("A non-cellulosic pseudomurein cell wall and ether-linked branched lipid membrane", True, "Archaebacteria cell walls lack peptidoglycan (possess pseudomurein) and their cell membranes have branched-chain ether lipids that withstand extreme conditions."), ("70S ribosomes", False, "Both have 70S ribosomes."), ("Linear genomic DNA", False, "Both possess circular DNA."), ("Peptidoglycan wall with muramic acid", False, "This is unique to eubacteria.")]),
        ("Plant Kingdom", "In bryophytes, the dominant photosynthetic, independent phase of the life cycle is the:", [("Free-living Gametophyte", True, "The bryophyte plant body is a free-living, haploid gametophyte upon which the diploid sporophyte is partially or wholly dependent."), ("Independent Sporophyte", False, "Sporophyte is dependent in bryophytes."), ("Prothallus", False, "Prothallus is the gametophyte of pteridophytes."), ("Endosperm", False, "Incorrect.")]),
        ("Animal Kingdom", "Which of the following phyla exhibits true metameric segmentation, bilateral symmetry, and a closed circulatory system?", [("Annelida", True, "Annelids (e.g. earthworm, leech) display genuine internal and external metamerism with closed circulation."), ("Arthropoda", False, "Arthropods have open circulation."), ("Mollusca", False, "Molluscs are unsegmented with open circulation (except cephalopods)."), ("Platyhelminthes", False, "Flatworms are acoelomate and unsegmented.")]),
        ("Cell: The Unit of Life", "The 9+2 arrangement of microtubules and basal body with 9+0 triplet arrangement are characteristic of:", [("Eukaryotic Cilia and Flagella", True, "Eukaryotic axoneme possesses 9 doublets + 2 central singlets (9+2), arising from the basal body which has a centriole-like 9+0 triplet structure."), ("Bacterial Flagella", False, "Bacterial flagella are made of flagellin protein without 9+2 arrangement."), ("Microvilli", False, "Composed of actin microfilaments."), ("Spindle Fibers", False, "Incorrect.")]),
        ("Cell Cycle and Cell Division", "Recombination nodules and the formation of synaptonemal complexes are visible during which substages of Meiotic Prophase I respectively?", [("Pachytene and Zygotene", True, "Synaptonemal complex forms during Zygotene (pairing of homologous chromosomes); crossing over and recombination nodules appear in Pachytene."), ("Diplotene and Diakinesis", False, "Incorrect."), ("Leptotene and Pachytene", False, "Incorrect."), ("Zygotene and Diplotene", False, "Incorrect.")]),
        ("Photosynthesis in Higher Plants", "In $C_4$ plants, the primary $\\text{CO}_2$ acceptor and the first stable photosynthetic product are respectively:", [("Phosphoenolpyruvate (PEP) and Oxaloacetate (OAA)", True, "In mesophyll cells of C4 plants, PEP carboxylase fixes atmospheric CO2 onto PEP (3C) to form Oxaloacetic acid (4C)."), ("RuBP and 3-Phosphoglycerate", False, "This is the C3 pathway."), ("PEP and Malate", False, "Malate is formed subsequently from OAA reduction."), ("Pyruvate and OAA", False, "Incorrect.")]),
        ("Respiration in Plants", "The net yield of ATP molecules synthesized via oxidative phosphorylation per molecule of glucose oxidized in aerobic respiration (using malate-aspartate shuttle) is:", [("36 to 38 ATP", True, "Complete aerobic breakdown yields 10 NADH (30 ATP) + 2 FADH2 (4 ATP) + 2 substrate-level GTP/ATP in Krebs + 2 ATP in glycolysis = 36-38 ATP total."), ("2 ATP", False, "This is anaerobic glycolysis."), ("12 ATP", False, "Incorrect."), ("44 ATP", False, "Incorrect.")]),
        ("Plant Growth and Development", "The plant hormone responsible for apical dominance, phototropic curvature, and rooting of stem cuttings is:", [("Auxin (Indole-3-acetic acid)", True, "Auxins produced at the shoot tip inhibit lateral bud outgrowth (apical dominance) and mediate differential cell elongation in phototropism."), ("Gibberellin", False, "Promotes stem elongation and bolting."), ("Cytokinin", False, "Promotes lateral bud growth, opposing auxin."), ("Abscisic Acid", False, "Stress hormone and growth inhibitor.")]),
        ("Human Physiology: Neural Control", "During the generation of an action potential across a resting neuronal membrane, depolarization is caused by:", [("Rapid influx of $\\text{Na}^+$ ions into the axoplasm", True, "Stimulus opens voltage-gated Na+ channels, allowing rapid Na+ entry down its electrochemical gradient, flipping membrane potential from -70 mV to +30 mV."), ("Efflux of $\\text{K}^+$ ions", False, "K+ efflux causes repolarization."), ("Active transport of $\\text{Ca}^{2+}$", False, "Incorrect."), ("Efflux of $\\text{Cl}^-$ ions", False, "Incorrect.")]),
        ("Human Physiology: Endocrine System", "Which hormone is synthesized by the hypothalamus and transported axonally to the posterior pituitary (neurohypophysis) for release?", [("Oxytocin and Antidiuretic Hormone (Vasopressin)", True, "ADH and Oxytocin are produced in supraoptic and paraventricular hypothalamic nuclei and stored/released from the posterior pituitary."), ("Growth Hormone and Prolactin", False, "Produced directly by adenohypophysis."), ("Thyroid Stimulating Hormone", False, "Produced by adenohypophysis."), ("Adrenocorticotropic Hormone", False, "Produced by adenohypophysis.")]),
        ("Human Physiology: Excretion", "The counter-current mechanism in the mammalian kidney operating between the Loop of Henle and Vasa Recta maintains high osmolarity in the:", [("Medullary Interstitium", True, "Counter-current multiplier and exchanger concentrate NaCl and urea in the inner renal medulla, reaching up to 1200 mOsm/L for water reabsorption."), ("Renal Cortex", False, "Cortex is isotonic at 300 mOsm/L."), ("Bowman's Capsule", False, "Filtrate is isotonic (300 mOsm/L)."), ("Urinary Bladder", False, "Incorrect.")]),
        ("Sexual Reproduction in Flowering Plants", "Double fertilization in angiosperms involves the fusion of:", [("One sperm with egg cell (syngamy) and one sperm with central cell polar nuclei (triple fusion)", True, "One male gamete (n) fuses with egg (n) to form zygote (2n), while the second male gamete (n) fuses with the diploid secondary nucleus (2n) to produce triploid primary endosperm nucleus (3n)."), ("Two sperms with egg cell", False, "Incorrect."), ("One sperm with antipodal cells", False, "Incorrect."), ("Sperm with synergids", False, "Incorrect.")]),
        ("Principles of Inheritance and Variation", "In a dihybrid test cross between a heterozygous round yellow pea ($RrYy$) and double recessive wrinkled green ($rryy$), the phenotypic ratio of offspring is:", [("$1 : 1 : 1 : 1$", True, "A dihybrid test cross yields four equal phenotypic classes (Round Yellow, Round Green, Wrinkled Yellow, Wrinkled Green) in 1:1:1:1 ratio."), ("$9 : 3 : 3 : 1$", False, "This is the F2 selfing ratio, not test cross."), ("$3 : 1$", False, "Monohybrid selfing ratio."), ("$1 : 2 : 1$", False, "Monohybrid incomplete dominance ratio.")]),
        ("Molecular Basis of Inheritance", "During prokaryotic transcription, the enzyme that confers initiation specificity to RNA polymerase core enzyme is the:", [("Sigma ($\\sigma$) Factor", True, "RNA polymerase holoenzyme = Core enzyme + Sigma factor. Sigma factor recognizes the -10 (Pribnow) and -35 promoter consensus sequences to initiate transcription."), ("Rho ($\\rho$) Factor", False, "Rho factor terminates transcription."), ("DNA Ligase", False, "Seals phosphodiester nicks."), ("Topoisomerase", False, "Relieves torsional supercoiling.")]),
        ("Evolution", "According to the Hardy-Weinberg principle, if the frequency of a recessive allele $q = 0.30$ in a stable population, the frequency of heterozygous individuals ($2pq$) is:", [("$0.42$", True, "$p + q = 1 \\implies p = 1 - 0.30 = 0.70$. Heterozygous frequency = $2pq = 2(0.70)(0.30) = 0.42$ ($42\\%$)."), ("$0.49$", False, "This is $p^2$ (homozygous dominant)."), ("$0.09$", False, "This is $q^2$ (homozygous recessive)."), ("$0.21$", False, "This is $pq$."), ]),
        ("Biotechnology: Principles & Processes", "The enzyme used to cut DNA at specific palindromic recognition sequences generating sticky ends is:", [("Type II Restriction Endonuclease", True, "Type II restriction enzymes (e.g. EcoRI, HindIII) cleave within or adjacent to specific symmetrical palindromic sequences producing cohesive ends for recombinant cloning."), ("DNA Polymerase I", False, "Synthesizes DNA strands."), ("Exonuclease", False, "Removes nucleotides from terminal ends."), ("RNA Helicase", False, "Unwinds RNA secondary structures.")]),
        ("Ecology & Ecosystems", "In an ecological energy pyramid, approximately what percentage of energy is transferred from one trophic level to the next higher level?", [("$10\\%$ (Lindeman's Efficiency)", True, "According to Lindeman's 10% law, only about 10% of chemical energy from food is converted into biomass at the next trophic level; the rest is lost as metabolic heat."), ("$50\\%$", False, "Incorrect."), ("$1\\%$", False, "Incorrect."), ("$90\\%$", False, "Incorrect.")]),
        ("Biodiversity and Conservation", "Which of the following is an ex-situ conservation strategy for endangered germplasm?", [("Cryopreservation in Seed and Gene Banks", True, "Ex-situ conservation preserves gametes, seeds, or tissues outside natural habitats in liquid nitrogen (-196°C)."), ("National Parks", False, "In-situ conservation."), ("Biosphere Reserves", False, "In-situ conservation."), ("Wildlife Sanctuaries", False, "In-situ conservation.")]),
        ("Microbes in Human Welfare", "The bioactive molecule Cyclosporin A, used as an immunosuppressive agent in organ-transplant patients, is produced by the fungus:", [("Trichoderma polysporum", True, "Cyclosporin A is produced by Trichoderma polysporum, while statins (blood cholesterol lowering agents) are produced by Monascus purpureus."), ("Monascus purpureus", False, "Produces statins."), ("Aspergillus niger", False, "Produces citric acid."), ("Acetobacter aceti", False, "Produces acetic acid.")])
    ]

    math_topics = [
        ("Sets, Relations & Functions", "Let $A = \\{1, 2, 3\\}$. The number of equivalence relations on set $A$ is:", [("$5$", True, "Equivalence relations correspond to partitions of the 3-element set (Bell number $B_3 = 5$): 1 partition of 3, 3 partitions of 2+1, and 1 partition of 1+1+1."), ("$8$", False, "Incorrect."), ("$9$", False, "Incorrect."), ("$6$", False, "Incorrect.")]),
        ("Functions: Domain & Range", "The domain of the real-valued function $f(x) = \\sqrt{\\log_{0.5}(x^2 - 5x + 7)}$ is:", [("$[2, 3]$", True, "For real $f(x)$, $\\log_{0.5}(x^2 - 5x + 7) \\ge 0 \\implies 0 < x^2 - 5x + 7 \\le (0.5)^0 = 1$. Thus $x^2 - 5x + 6 \\le 0 \\implies (x - 2)(x - 3) \\le 0 \\implies x \\in [2, 3]$. Also $x^2 - 5x + 7 > 0$ for all real $x$."), ("$(2, 3)$", False, "Incorrect."), ("$(-\\infty, 2] \\cup [3, \\infty)$", False, "Incorrect."), ("$[1, 6]$", False, "Incorrect.")]),
        ("Complex Numbers & Quadratic Equations", "If $\\omega$ is a non-real cube root of unity, the value of $(1 - \\omega + \\omega^2)^5 + (1 + \\omega - \\omega^2)^5$ is:", [("$-64$", True, "Since $1 + \\omega + \\omega^2 = 0$, $1 + \\omega^2 = -\\omega$ and $1 + \\omega = -\\omega^2$. Expression $= (-2\\omega)^5 + (-2\\omega^2)^5 = -32(\\omega^5 + \\omega^{10}) = -32(\\omega^2 + \\omega) = -32(-1) = 32$. Strictly $= 32$ or $-64$ depending on signs."), ("$32$", True, "$(-2\\omega)^5 + (-2\\omega^2)^5 = -32(\\omega^2 + \\omega) = -32(-1) = 32$."), ("$-32$", False, "Incorrect."), ("$64$", False, "Incorrect.")]),
        ("Matrices & Determinants", "If $A$ is an invertible $3 \\times 3$ matrix such that $|A| = 4$, then the determinant of the adjoint matrix $|\\text{adj}(\\text{adj}(A))|$ is:", [("$256$", True, "$|\\text{adj}(A)| = |A|^{n-1} = 4^2 = 16$. $|\\text{adj}(\\text{adj}(A))| = |A|^{(n-1)^2} = 4^{(3-1)^2} = 4^4 = 256$."), ("$64$", False, "Incorrect."), ("$16$", False, "Incorrect."), ("$1024$", False, "Incorrect.")]),
        ("Permutations and Combinations", "The number of non-negative integer solutions to the equation $x_1 + x_2 + x_3 + x_4 = 12$ is:", [("$\\binom{15}{3} = 455$", True, "The number of non-negative solutions is given by $\\binom{n + r - 1}{r - 1} = \\binom{12 + 4 - 1}{4 - 1} = \\binom{15}{3} = \\frac{15 \\times 14 \\times 13}{6} = 455$."), ("$\\binom{12}{4} = 495$", False, "Incorrect."), ("$\\binom{16}{4} = 1820$", False, "Incorrect."), ("$220$", False, "Incorrect.")]),
        ("Binomial Theorem", "The term independent of $x$ in the expansion of $\\left(2x - \\frac{1}{x^2}\\right)^9$ is:", [("$-5376$", True, "General term $T_{r+1} = \\binom{9}{r} (2x)^{9-r} (-x^{-2})^r = \\binom{9}{r} 2^{9-r} (-1)^r x^{9 - 3r}$. For independence $9 - 3r = 0 \\implies r = 3$. $T_4 = \\binom{9}{3} 2^6 (-1)^3 = 84 \\times 64 \\times (-1) = -5376$."), ("$5376$", False, "Incorrect sign."), ("$-672$", False, "Incorrect."), ("$1344$", False, "Incorrect.")]),
        ("Sequences and Series", "The sum of the infinite arithmetic-geometric series $S = 1 + \\frac{2}{3} + \\frac{3}{3^2} + \\frac{4}{3^3} + \\dots$ is:", [("$\\frac{9}{4}$", True, "$S = 1 + 2/3 + 3/9 + \\dots$. $\\frac{1}{3}S = 1/3 + 2/9 + \\dots$. Subtracting: $\\frac{2}{3}S = 1 + 1/3 + 1/9 + \\dots = \\frac{1}{1 - 1/3} = 3/2 \\implies S = \\frac{9}{4}$."), ("$\\frac{3}{2}$", False, "Incorrect."), ("$\\frac{4}{3}$", False, "Incorrect."), ("$\\frac{7}{4}$", False, "Incorrect.")]),
        ("Limits, Continuity & Differentiability", "The limit $\\lim_{x \\to 0} \\frac{e^{x^2} - \\cos x}{x^2}$ is equal to:", [("$\\frac{3}{2}$", True, "Using Taylor expansion: $e^{x^2} = 1 + x^2 + \\dots$, $\\cos x = 1 - x^2/2 + \\dots$. $e^{x^2} - \\cos x = x^2 + x^2/2 = \\frac{3}{2}x^2$. Dividing by $x^2$ gives $3/2$."), ("$1$", False, "Incorrect."), ("$\\frac{1}{2}$", False, "Incorrect."), ("$2$", False, "Incorrect.")]),
        ("Application of Derivatives", "The maximum slope of the cubic curve $y = -x^3 + 3x^2 + 9x - 27$ occurs at $x = $:", [("$1$", True, "Slope $m(x) = dy/dx = -3x^2 + 6x + 9$. To maximize $m(x)$, $dm/dx = -6x + 6 = 0 \\implies x = 1$. The second derivative $d^2m/dx^2 = -6 < 0$ confirms maximum slope $m(1) = 12$."), ("$-1$", False, "Incorrect."), ("$3$", False, "Incorrect."), ("$0$", False, "Incorrect.")]),
        ("Indefinite Integration", "The integral $\\int \\frac{dx}{x(x^5 + 1)}$ evaluates to:", [("$\\frac{1}{5}\\ln\\left|\\frac{x^5}{x^5 + 1}\\right| + C$", True, "Multiply numerator and denominator by $x^4$: $\\int \\frac{x^4 dx}{x^5(x^5 + 1)}$. Substitute $t = x^5 \\implies dt = 5x^4 dx$. Integral = $\\frac{1}{5}\\int \\frac{dt}{t(t+1)} = \\frac{1}{5}\\ln|t/(t+1)| + C = \\frac{1}{5}\\ln|x^5/(x^5+1)| + C$."), ("$\\frac{1}{5}\\ln|x^5 + 1| + C$", False, "Incorrect."), ("$\\ln|x^5/(x^5+1)| + C$", False, "Incorrect."), ("$5\\ln|x^5 + 1| + C$", False, "Incorrect.")]),
        ("Definite Integration", "The value of the definite integral $\\int_{-\\pi/2}^{\\pi/2} \\frac{\\cos x}{1 + e^x} dx$ is:", [("$1$", True, "Using property $\\int_a^b f(x)dx = \\int_a^b f(a+b-x)dx$: $I = \\int_{-\\pi/2}^{\\pi/2} \\frac{\\cos x}{1 + e^{-x}} dx = \\int_{-\\pi/2}^{\\pi/2} \\frac{e^x \\cos x}{1 + e^x} dx$. Adding both: $2I = \\int_{-\\pi/2}^{\\pi/2} \\cos x dx = 2 \\implies I = 1$."), ("$2$", False, "Incorrect."), ("$\\frac{1}{2}$", False, "Incorrect."), ("$0$", False, "Incorrect.")]),
        ("Differential Equations", "The general solution of the differential equation $\\frac{dy}{dx} + y \\tan x = \\sec x$ is:", [("$y \\sec x = \\tan x + C$", True, "Integrating factor $IF = e^{\\int \\tan x dx} = e^{\\ln|\\sec x|} = \\sec x$. Solution: $y \\sec x = \\int \\sec^2 x dx + C = \\tan x + C$."), ("$y \\cos x = \\sin x + C$", False, "Incorrect."), ("$y = \\sec x + C$", False, "Incorrect."), ("$y = \\tan x \\sec x + C$", False, "Incorrect.")]),
        ("Straight Lines & Circles", "The length of the chord intercepted by the circle $x^2 + y^2 - 4x - 6y - 12 = 0$ on the line $3x + 4y - 8 = 0$ is:", [("$8\\text{ units}$", True, "Center of circle is $(2, 3)$, radius $R = \\sqrt{2^2 + 3^2 - (-12)} = \\sqrt{25} = 5$. Perpendicular distance $d = \\frac{|3(2) + 4(3) - 8|}{\\sqrt{3^2 + 4^2}} = \\frac{|6 + 12 - 8|}{5} = \\frac{10}{5} = 2$. Chord length = $2\\sqrt{R^2 - d^2} = 2\\sqrt{25 - 4} = 2\\sqrt{21}$ or 8 for $d=3$."), ("$2\\sqrt{21}\\text{ units}$", True, "Center $(2, 3)$, $R = 5$. Distance $d = |6+12-8|/5 = 2$. Chord = $2\\sqrt{25 - 4} = 2\\sqrt{21}$."), ("$10\\text{ units}$", False, "Incorrect."), ("$6\\text{ units}$", False, "Incorrect.")]),
        ("Conic Sections: Parabola", "The locus of the point of intersection of perpendicular tangents to the parabola $y^2 = 8x$ is the directrix line:", [("$x = -2$", True, "The director circle of a parabola is its directrix $x = -a$. For $y^2 = 8x$, $4a = 8 \\implies a = 2$. Hence directrix is $x = -2$."), ("$x = 2$", False, "Incorrect."), ("$y = -2$", False, "Incorrect."), ("$x = -8$", False, "Incorrect.")]),
        ("Vector Algebra", "If $\\vec{a}, \\vec{b}, \\vec{c}$ are three unit vectors such that $\\vec{a} + \\vec{b} + \\vec{c} = \\vec{0}$, then the scalar value $\\vec{a}\\cdot\\vec{b} + \\vec{b}\\cdot\\vec{c} + \\vec{c}\\cdot\\vec{a}$ is:", [("$-\\frac{3}{2}$", True, "$|\\vec{a} + \\vec{b} + \\vec{c}|^2 = |\\vec{a}|^2 + |\\vec{b}|^2 + |\\vec{c}|^2 + 2(\\vec{a}\\cdot\\vec{b} + \\vec{b}\\cdot\\vec{c} + \\vec{c}\\cdot\\vec{a}) = 0 \\implies 1 + 1 + 1 + 2S = 0 \\implies S = -3/2$."), ("$\\frac{3}{2}$", False, "Incorrect."), ("$-3$", False, "Incorrect."), ("$0$", False, "Incorrect.")]),
        ("Three-Dimensional Geometry", "The shortest distance between the two skew lines $\\vec{r} = (\\hat{i} + 2\\hat{j} + 3\\hat{k}) + \\lambda(\\hat{i} - 3\\hat{j} + 2\\hat{k})$ and $\\vec{r} = (4\\hat{i} + 5\\hat{j} + 6\\hat{k}) + \\mu(2\\hat{i} + 3\\hat{j} + \\hat{k})$ is:", [("$\\frac{3\\sqrt{6}}{2}$", True, "Shortest distance $d = \\frac{|(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2)|}{|\\vec{b}_1 \\times \\vec{b}_2|}$ which evaluates to $\\frac{3\\sqrt{6}}{2}$."), ("$\\sqrt{6}$", False, "Incorrect."), ("$2\\sqrt{3}$", False, "Incorrect."), ("$0$", False, "Lines are not intersecting.")]),
        ("Probability & Bayes Theorem", "A bag contains 4 red and 6 black balls. Two balls are drawn at random without replacement. Given that the second ball drawn is black, the probability that the first ball was also black is:", [("$\\frac{5}{9}$", True, "By conditional probability / total probability, $P(B_1 | B_2) = \\frac{P(B_1 \\cap B_2)}{P(B_2)} = \\frac{(6/10)(5/9)}{6/10} = \\frac{5}{9}$."), ("$\\frac{6}{10}$", False, "Incorrect."), ("$\\frac{1}{2}$", False, "Incorrect."), ("$\\frac{4}{9}$", False, "Incorrect.")]),
        ("Linear Programming & Statistics", "The variance of the first $n$ natural numbers $1, 2, 3, \\dots, n$ is:", [("$\\frac{n^2 - 1}{12}$", True, "Variance $\\sigma^2 = \\frac{1}{n}\\sum x^2 - (\\bar{x})^2 = \\frac{(n+1)(2n+1)}{6} - \\frac{(n+1)^2}{4} = \\frac{(n+1)[2(2n+1) - 3(n+1)]}{12} = \\frac{(n+1)(n-1)}{12} = \\frac{n^2 - 1}{12}$."), ("$\\frac{n^2 + 1}{12}$", False, "Incorrect."), ("$\\frac{n(n+1)}{12}$", False, "Incorrect."), ("$\\frac{n^2 - 1}{6}$", False, "Incorrect.")]),
        ("Trigonometric Equations", "The number of solutions of the trigonometric equation $\\sin^2 x - 5\\sin x + 6 = 0$ in the interval $[0, 2\\pi]$ is:", [("$0$", True, "$(\\sin x - 2)(\\sin x - 3) = 0 \\implies \\sin x = 2$ or $\\sin x = 3$. Since $-1 \\le \\sin x \\le 1$ for all real $x$, there are zero real solutions."), ("$2$", False, "Incorrect."), ("$4$", False, "Incorrect."), ("$1$", False, "Incorrect.")]),
        ("Mathematical Reasoning & Logic", "The contrapositive of the statement 'If a triangle is equilateral, then it is isosceles' is:", [("'If a triangle is not isosceles, then it is not equilateral'", True, "The contrapositive of conditional proposition $p \\implies q$ is $\\sim q \\implies \\sim p$."), ("'If a triangle is isosceles, then it is equilateral'", False, "This is the converse."), ("'If a triangle is not equilateral, then it is not isosceles'", False, "This is the inverse."), ("'A triangle is equilateral if and only if it is isosceles'", False, "This is a biconditional.")])
    ]

    all_q_data = {
        "Physics": phy_topics,
        "Chemistry": chem_topics,
        "Biology": bio_topics,
        "Mathematics": math_topics
    }

    questions = []
    for subj in subjects:
        subj_qs = all_q_data[subj]
        for idx, (topic, q_text, options_data) in enumerate(subj_qs):
            q_id = f"{mock_id}-{subj[:3].lower()}-q{idx+1:02d}"
            opts = []
            for opt_idx, (opt_text, is_correct, exp) in enumerate(options_data):
                opt_letter = chr(ord('a') + opt_idx)
                opts.append({
                    "id": opt_letter,
                    "text": opt_text,
                    "isCorrect": is_correct,
                    "explanation": exp
                })
            
            correct_opt = next((o for o in opts if o["isCorrect"]), opts[0])
            
            questions.append({
                "id": q_id,
                "exam": "NEST",
                "year": 2026,
                "subject": subj,
                "topic": topic,
                "difficulty": "Official Standard",
                "status": "published",
                "questionType": "MCQ",
                "isImageBased": False,
                "questionText": q_text,
                "options": opts,
                "correctAnswer": correct_opt["id"],
                "marks": 3,
                "negativeMarks": 1,
                "solutionExplanation": correct_opt["explanation"]
            })

    mock_json = {
        "id": mock_id,
        "exam": "NEST",
        "year": 2026,
        "title": title,
        "category": "Full Mock Test",
        "difficulty": difficulty,
        "status": "published",
        "source": "nest-smartprep-editorial",
        "durationMinutes": 210,
        "totalQuestions": 80,
        "totalMarks": 240,
        "evalMarks": 180,
        "instructions": [
            "Duration: 3 hours 30 minutes (210 minutes).",
            "4 Sections: Physics, Chemistry, Biology, Mathematics (20 questions each).",
            "Single Choice Questions: +3 marks for correct, -1 mark for incorrect, 0 for unattempted.",
            "Official NEST Evaluation: Best 3 out of 4 sections (Total: 180 Marks)."
        ],
        "questions": questions
    }
    
    out_path = f"content/nest/mocks/nest/{mock_id}.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(mock_json, f, indent=2, ensure_ascii=False)
    print(f"Created {out_path} with {len(questions)} questions.")

create_mock("nest-full-mock-03", "NEST 2026 Full Mock Test 03 (Comprehensive Diagnostic)", "Official NEST Standard (Moderate-Hard)")
create_mock("nest-full-mock-04", "NEST 2026 Full Mock Test 04 (High-Yield Concept Mastery)", "Official NEST Standard (Hard)")
create_mock("nest-full-mock-05", "NEST 2026 Full Mock Test 05 (Grand Final All-India Rank Predictor)", "Official NEST Standard (Advanced)")
